### ISSUE TITLE
Doesn't work - flatpak on opensuse leap 15

### ISSUE THREAD

**Issue by RDKRACZ** [SeaDve/Kooha#159] opened 2022-03-06 11:05 UTC
**System Info**
- Kooha version 2.0.1 from flathub
- Distro information and version openSUSE Leap 15.3
- Desktop Environment information and version KDE 5.24.2
- Display Server X11
- Flatpak? Ye

**Describe the bug**
![Screenshot_20220306_115603](https://user-images.githubusercontent.com/43277609/156920204-72bdef79-a850-42c2-8df7-20ff0f6e1345.png)

**Additional context**
If applicable, please attach the logs from running Kooha with the following 
environment variables `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3` while running kooha

```
(kooha:2): Gtk-WARNING **: 12:01:05.767: Locale not supported by C library.
        Using the fallback 'C' locale.
 INFO  kooha::application > Kooha (io.github.seadve.Kooha)
 INFO  kooha::application > Version: 2.0.1 ()
 INFO  kooha::application > Datadir: /app/share/kooha
 DEBUG kooha::backend::recorder > is_show_pointer: true
 DEBUG kooha::backend::recorder > is_selection_mode: false
 INFO  kooha::backend::screencast_portal > ScreenCastProxy created
 DEBUG kooha::backend::screencast_portal > available_cursor_modes: BitFlags<CursorMode>(0b111, Hidden | Embedded | Metadata)
 DEBUG kooha::backend::screencast_portal > available_source_types: BitFlags<SourceType>(0b11, Monitor | Window)
 ERROR kooha::backend::screencast_portal > Error from screencast call: Response(Other)
```

**Comment by SeaDve** [comment] 2022-03-06 11:44
Might be related with #60

**Comment by stpnwf** [comment] 2022-05-03 17:02
Get the same error message on Gnome 38 on Zorin OS 16

**Comment by SeaDve** [comment] 2022-08-16 11:39
Thanks for submitting an issue! I'll close this though as a duplicate of #129. And checking out this [comment](https://github.com/SeaDve/Kooha/issues/129#issuecomment-1060293459) may be helpful.

**Closed by SeaDve** 2022-08-16 11:39 UTC
