### ISSUE TITLE
Area selection doesn't work with multiple monitors

### ISSUE THREAD

**Issue by Hofer-Julian** [SeaDve/Kooha#162] opened 2022-03-24 13:47 UTC
**System Info**
- Kooha version 2.0.1
- Distro information and version: Fedora 35 Workstation
- Desktop Environment information and version: GNOME 41,
- Display Server: Wayland
- Flatpak: yes

**Describe the bug**
When you have multiple monitors and you want to record a selection of it, it always asks you to draw the selection on the same monitor. But then it records it one the monitor you've selected in the first place

**To Reproduce**
1. Record selection of monitor
2. Choose the monitor
3. It always asks you to draw the selection on the same monitor (in my case left)
4. It actually records on the one that you chose in step 2

Sidenote: I have two monitors with the same name. Not sure if that is necessary to reproduce the bug.

**Screenshots**

**Additional context**
If applicable, please attach the logs from running Kooha with the following 
environment variables `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3`
while running kooha (e.g. `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 flatpak run io.github.seadve.Kooha`)

**Comment by xVANKO** [comment] 2022-04-21 09:48
I confirm this issue

**Comment by asjur** [comment] 2022-04-25 12:00
I can confirm that having multiple monitors with different names experiences the same bug.

**Comment by skerit** [comment] 2022-07-07 10:42
The issue also exists when having multiple identical monitors.
In fact, it's even a bit worse because you then get this screen:
![afbeelding](https://user-images.githubusercontent.com/755212/177755361-e799d9ae-9c36-4630-b8f8-e165e65de697.png)

**Comment by SeaDve** [comment] 2022-08-15 03:13
Closing this in favor of #153

**Closed** 2022-08-15 03:15 UTC
