### ISSUE TITLE
Area can only be selected on built-in laptop monitor (gnome wayland)

### ISSUE THREAD

**Issue by alxckn** [SeaDve/Kooha#153] opened 2022-01-18 15:11 UTC
**System Info**
- Kooha version: 2.0.1
- Distro information and version: Fedora 35
- Desktop Environment information and version: GNOME 41
- Display Server: Wayland
- Flatpak: Yes (also tried building from source, same issue)

**Describe the bug**
When using multiple screens and the selection feature, the selectable area will always be the builtin screen no matter which screen was chosen with the xdg-portal modal.

**To Reproduce**
1. Start a screen recording using the 'Selection' mode:
![image](https://user-images.githubusercontent.com/11556013/149962509-849fb6a3-547e-4fce-bf7b-fa9efb7d3725.png)
2. Select a monitor which is not the built in one
![image](https://user-images.githubusercontent.com/11556013/149962624-5c34a852-5779-424a-8823-75be59afe6a6.png)
3. See issue: the cross pointer only appears on the builtin screen and selection can only happen on the built in screen

Note: while the selection can only be done on the built in screen, the recording will be made with the screen chosen at step 2 and it will have approximately applied the coordinates chosen on the builtin screen.

**Expected behavior**
After selecting a screen, the selection tool should be available on that screen so that the selection area can be defined precisely.

**Additional context**

<details>
<summary>Logs</summary>
Application started at 04:08:45 PM
 INFO  kooha::application > Kooha (io.github.seadve.Kooha.Devel)
 INFO  kooha::application > Version: 2.0.1-d2e4957 (Devel)
 INFO  kooha::application > Datadir: /app/share/kooha

(kooha:2): Gtk-CRITICAL **: 16:08:45.504: Unable to connect to the accessibility bus at 'unix:abstract=00009': Could not connect: Connection refused
 DEBUG kooha::backend::recorder > is_show_pointer: true
 DEBUG kooha::backend::recorder > is_selection_mode: true
 INFO  kooha::backend::screencast_portal > ScreenCastProxy created
 DEBUG kooha::backend::screencast_portal > available_cursor_modes: BitFlags<CursorMode>(0b111, Hidden | Embedded | Metadata)
 DEBUG kooha::backend::screencast_portal > available_source_types: BitFlags<SourceType>(0b11, Monitor | Window)
 INFO  kooha::backend::screencast_portal > Session created
 INFO  kooha::backend::screencast_portal > Select sources window showed
 INFO  kooha::backend::screencast_portal > Screencast session started
 INFO  kooha::backend::screencast_portal > Ready for pipewire stream
 DEBUG kooha::backend::recorder          > pulse_server_version: PulseAudio (on PipeWire 0.3.40) version 15.0.0
 WARN  kooha::widgets::area_selector     > Failed to set raise active window to true: 
 WARN  kooha::widgets::area_selector     > Failed to set raise active window to false: 
 DEBUG kooha::backend::recorder          > PipelineBuilder { is_record_speaker: false, is_record_mic: false, framerate: 30, file_path: "/home/alexandre.chakroun/Videos/Kooha-2022-01-18-16-08-49.webm", fd: 19, streams: [Stream { pipewire_node_id: 106, position: Some((1920, 0)), size: Some((1920, 1080)) }], speaker_source: Some("alsa_output.usb-GN_Netcom_A_S_Jabra_EVOLVE_LINK_MS_0011D0FF6D4E0A-00.analog-stereo.monitor"), mic_source: Some("alsa_input.usb-GN_Netcom_A_S_Jabra_EVOLVE_LINK_MS_0011D0FF6D4E0A-00.mono-fallback"), coordinates: Some(Rectangle { x: 550.35546875, y: 316.55859375, width: 877.78125, height: 454.9375 }), actual_screen: Some(Screen { width: 1920, height: 1080 }) }
 DEBUG kooha::backend::pipeline_builder  > is_use_vaapi: false
 DEBUG kooha::backend::pipeline_builder  > pipeline_string: queue name=queue0 ! videorate ! video/x-raw, framerate=30/1 ! videoscale ! video/x-raw, width=1920, height=1080 ! videocrop top=316 left=550 right=490 bottom=308 ! videoconvert chroma-mode=GST_VIDEO_CHROMA_MODE_NONE dither=GST_VIDEO_DITHER_NONE matrix-mode=GST_VIDEO_MATRIX_MODE_OUTPUT_ONLY n-threads=8 ! queue ! vp8enc max_quantizer=17 cpu-used=16 cq_level=13 deadline=1 static-threshold=100 keyframe-mode=disabled buffer-size=20000 threads=8 ! queue ! webmmux name=mux ! filesink name=filesink location="/home/alexandre.chakroun/Videos/Kooha-2022-01-18-16-08-49.webm" pipewiresrc fd=19 path=106 do-timestamp=true keepalive-time=1000 resend-last=true ! video/x-raw, max-framerate=30/1 ! queue0. 
[I][24857.998976][      pipewire.c:  571 pw_init()] version 0.3.35
[I][24858.014588][          conf.c:  326 conf_load()] config 0x55c53b84f3a0: loading config '/usr/share/pipewire/client.conf'
[I][24858.014665][       context.c:  384 pw_context_new()] context 0x55c53b8566e0: parsed context.properties section
[I][24858.015453][       context.c:  478 pw_context_new()] context 0x55c53b8566e0: parsed 2 context.spa-libs items
[I][24858.015942][          conf.c:  419 load_module()] config 0x55c53b8566e0: loaded module libpipewire-module-protocol-native
[I][24858.016498][          conf.c:  419 load_module()] config 0x55c53b8566e0: loaded module libpipewire-module-client-node
[I][24858.016777][          conf.c:  419 load_module()] config 0x55c53b8566e0: loaded module libpipewire-module-client-device
[I][24858.017092][          conf.c:  419 load_module()] config 0x55c53b8566e0: loaded module libpipewire-module-adapter
[I][24858.017368][          conf.c:  419 load_module()] config 0x55c53b8566e0: loaded module libpipewire-module-metadata
[I][24858.017745][          conf.c:  419 load_module()] config 0x55c53b8566e0: loaded module libpipewire-module-session-manager
[I][24858.017760][       context.c:  482 pw_context_new()] context 0x55c53b8566e0: parsed 6 context.modules items
[I][24858.017776][       context.c:  487 pw_context_new()] context 0x55c53b8566e0: parsed 0 context.objects items
[I][24858.017786][       context.c:  490 pw_context_new()] context 0x55c53b8566e0: parsed 0 context.exec items
[I][24858.017853][       context.c:  244 context_set_freewheel()] context 0x55c53b8566e0: exit freewheel
[I][24858.017875][       context.c:  248 context_set_freewheel()] context 0x55c53b8566e0: freewheel error:Operation not supported
[I][24858.017891][ impl-metadata.c:  196 impl_set_property()] metadata 0x55c53b858290: add id:0 key:log.level type: value:0
[I][24858.017900][ impl-metadata.c:  196 impl_set_property()] metadata 0x55c53b858290: add id:0 key:clock.min-quantum type: value:32
[I][24858.017907][ impl-metadata.c:  196 impl_set_property()] metadata 0x55c53b858290: add id:0 key:clock.max-quantum type: value:8192
[I][24858.017915][ impl-metadata.c:  196 impl_set_property()] metadata 0x55c53b858290: add id:0 key:clock.force-quantum type: value:0
[I][24858.017926][ impl-metadata.c:  196 impl_set_property()] metadata 0x55c53b858290: add id:0 key:clock.force-rate type: value:0
0:00:06.420086223     2 0x55c53a5d4a40 FIXME                default gstutils.c:4025:gst_pad_create_stream_id_internal:<pipewiresrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
[I][24858.087043][     impl-node.c:  358 node_update_state()] (kooha-0) creating -> running
 INFO  kooha::backend::recorder          > Captured coordinates
 INFO  kooha::backend::recorder          > Pipeline state set from Null -> Ready
 INFO  kooha::backend::recorder          > Pipeline state set from Ready -> Paused
0:00:06.560300005     2 0x7fa234083520 FIXME               basesink gstbasesink.c:3388:gst_base_sink_default_event:<filesink> stream-start event without group-id. Consider implementing group-id handling in the upstream elements
 INFO  kooha::backend::recorder          > Pipeline state set from Paused -> Playing
 INFO  kooha::backend::recorder          > Sending eos event to pipeline
[I][24861.721801][     impl-node.c:  358 node_update_state()] (kooha-0) running -> idle
[I][24861.727118][     impl-node.c:  358 node_update_state()] (kooha-0) idle -> suspended
[I][24861.727232][     impl-node.c: 1736 pw_impl_node_destroy()] (kooha-0) destroy
 INFO  kooha::backend::screencast_portal > Session closed
 INFO  kooha::backend::recorder          > Eos signal received from record bus
Application exited
</details>

**Comment by simonleber** [comment] 2022-01-20 08:29
I came here to report that exact same bug. Happy to help testing or supply any further logs or system configuration details

**Comment by SeaDve** [comment] 2022-01-25 08:13
It's hard to fix this due to limitations in wayland. This may be a semi duplicate of this https://github.com/SeaDve/Kooha/issues/113

For now, I believe you can move Kooha's main window to the monitor where you would record and it shall spawn the AreaSelector on where Kooha is.

**Comment by alxckn** [comment] 2022-01-26 11:02
Hello @SeaDve, thank you for your response.

> For now, I believe you can move Kooha's main window to the monitor where you would record and it shall spawn the AreaSelector on where Kooha is.
Unfortunately no, it does not seem to matter where Kooha's main window is, the selection can only occur on the builtin display.

I can run specific tests or configurations if that can help narrow down the issue

**Comment by Yajo** [comment] 2022-02-10 10:17
Just a couple of details to add:

1. In Xorg, the same happens.
2. In my case, the laptop's built-in monitor is the only one where you can drag the window portion. However, the monitor that is configured as "main" in gnome settings is the external one. So the issue title seems a bit misleading: it should be "built-in", not "main" monitor FWIW.
3. Dragging a selection in built-in monitor starts recording in external monitor, if that's the one that was selected.

**Comment by adueppen** [comment] 2022-02-24 22:35
I'm experiencing this too, one workaround I have found is that I can go into the overview and drag the selection overlay window onto the display it should be on and then make my selection.

**Comment by SeaDve** [comment] 2022-08-15 03:15
The wayland-appropriate solution I can think of is to implement area selection similar to OBS, where the area selection is within the Kooha's window.

**Comment by SeaDve** [comment] 2022-09-28 03:32
This is now fixed on the main branch with a new non-hacky area selector: 

https://github.com/SeaDve/Kooha/commit/b025b8ad5d6d36f6b261e8c175eb77518690ff11

![image](https://user-images.githubusercontent.com/64297935/192681200-91ced554-4147-440e-badf-1770901647d1.png)

**Closed** 2022-09-28 03:32 UTC
Labels: bug
