### ISSUE TITLE
Request: Save recordings as .gif

### ISSUE THREAD

**Issue by rockerbacon** [SeaDve/Kooha#12] opened 2021-03-15 19:49 UTC
My use case for screen recordings is to send small GUI demos to colleagues and sometimes show bugs in a more visual manner. For this use case, being able to send gifs is extremely useful because some platforms (like GitHub) do not support videos. Having the gif playing automatically without the need for them to open a video is also very convenient.

**Comment by SeaDve** [comment] 2021-03-15 23:05
For now, I do not have plans on implementing GIF recording since we already have peek which greatly do it. Maybe if gstreamer will support encoding directly encoding to GIF without workarounds.

**Comment by rrobertobt** [comment] 2021-04-09 06:01
> For now, I do not have plans on implementing GIF recording since we already have peek which greatly do it. Maybe if gstreamer will support encoding directly encoding to GIF without workarounds.
> 
> I think GitHub already support mp4 Videos

The problem is that Peek doesn't support Wayland :(

**Comment by SeaDve** [comment] 2021-06-09 03:54
I'm considering on supporting this on 2.0.0 #65

**Comment by SeaDve** [comment] 2021-06-09 03:59
Had been experimenting with it, but still haven't found a clean way to do it, and there's color issues
![Kooha 06-09-2021 11:57:01](https://user-images.githubusercontent.com/64297935/121290980-16930a80-c91a-11eb-9157-d36e2303a1ce.gif)

**Comment by SeaDve** [comment] 2021-06-23 13:53
gif now works, without workarounds :D check $81

**Comment by SeaDve** [comment] 2021-06-24 01:18
![Kooha 06-24-2021 09:16:23](https://user-images.githubusercontent.com/64297935/123187587-090a8280-d4cd-11eb-8280-a92c0fd7e0a8.gif)

**Comment by rrobertobt** [comment] 2021-06-24 01:20
Now I can't wait to try the 2.0 release! :) Thank you for this awesome app.

**Comment by SeaDve** [comment] 2021-07-02 00:54
Support has been merged to main branch, closing this :D

**Closed by SeaDve** 2021-07-02 00:54 UTC
Labels: enhancement
