### ISSUE TITLE
Failed to start recording

### ISSUE THREAD

**Issue by mcmuffin6o** [SeaDve/Kooha#256] opened 2023-10-20 23:08 UTC
Failed to start recording

Caused by:
    0: Check out <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> for help.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Failed to call `CreateSession` with parameters: Variant { ptr: 0x55da3904ee90, type: VariantTy { inner: "(a{sv})" }, value: "({'handle_token': <'kooha_1'>, 'session_handle_token': <'kooha_0'>},)" }
    4: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

**Comment by mooreye** [comment] 2023-10-21 14:59
I have the same issue.

```
Failed to start recording

Caused by:
    0: Check out <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> for help.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Failed to call `CreateSession` with parameters: Variant { ptr: 0x55cf08a53de0, type: VariantTy { inner: "(a{sv})" }, value: "({'handle_token': <'kooha_1'>, 'session_handle_token': <'kooha_0'>},)" }
    4: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
```

**Comment by mefistotelis** [comment] 2023-10-21 16:58
> No such interface “org.freedesktop.portal.ScreenCast”

Then install a package which provides that interface?
Pity the strange package system used by this app can't automatically solve dependencies, like apt/rpm does.

Not an expert, but I think `[xdg-desktop-portal](https://www.freshports.org/deskutils/xdg-desktop-portal)` provides this. If not, google the error to find package name to install.

**Comment by mcmuffin6o** [comment] 2023-10-21 21:08
> Pity the strange package system used by this app can't automatically solve dependencies, like apt/rpm does.

Exactly. I'm not gonna install a bunch of random crap that I'll have to manually keep track of and remove when I inevitably come up short attempting to play FOSS whackamole.

**Comment by SeaDve** [comment] 2024-02-08 12:49
Closing as duplicate of https://github.com/SeaDve/Kooha/issues/129.

**Closed by SeaDve** 2024-02-08 12:49 UTC
