### ISSUE TITLE
Option for native quality screencast

### ISSUE THREAD

**Issue by yioannides** [SeaDve/Kooha#312] opened 2024-08-10 17:56 UTC
**Feature summary**

It would be nice to have an option to record video on very high quality, close to one's native resolution, like OBS's "Indistinguishable quality, Large File Size" option, that delivers almost native quality.

I am not sure if it's due to [GNOME's lack of hardware encoding for screencasts](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2080) or not, but so far, no screencast software can deliver high quality or lossless video recording.

**How would you like it to work**

An additional option in the menu, for video recording quality.

**Comment by SeaDve** [comment] 2024-08-15 02:13
Thanks for reporting! However, I see that this seems a duplicate of #31.

**Closed by SeaDve** 2024-08-15 02:13 UTC
Labels: enhancement
