### ISSUE TITLE
Support Sway WM

### ISSUE THREAD

**Issue by faern** [SeaDve/Kooha#42] opened 2021-03-28 11:49 UTC
Nice screen recording program!

Upon starting it I noticed it says "sway is not yet supported" (version 1.1.0). And I saw no mention of it in the issue tracker. So I figured I might create this issue as a feature request + tracking issue people can follow if there happens to be updates regarding support for Sway.

Thank you.

**Comment by SeaDve** [comment] 2021-03-28 11:54
thanks! If sway support freedesktop.portal.ScreenCast there is likely a support incoming in v2.0.0

**Comment by SeaDve** [comment] 2021-05-26 12:03
#65 if sway support org.freedesktop.portal.Screencast

**Comment by faern** [comment] 2021-05-28 11:16
If you install `xdg-desktop-portal` and `xdg-desktop-portal-wlr` then sway should support it. So sounds good! :+1:

**Comment by SeaDve** [comment] 2021-05-28 11:18
Does it have to packaged, or just installed with your system?

**Comment by faern** [comment] 2021-05-28 17:55
I have not tried this myself. But I think you can just install those packages on your system (and maybe run them in the background)?

**Comment by p00f** [comment] 2021-06-25 11:44
I have `xdg-desktop-portal`, `xdg-desktop-portal-wlr` and `xdg-desktop-portal-gtk` running in sway, kooha still says "sway not supported"

**Comment by SeaDve** [comment] 2021-06-25 11:51
you'll have to either build from source or get the artifact from github action.

Flathub and aur versions are still the old 1.2.1

**Comment by p00f** [comment] 2021-06-25 12:02
Oh I see, thanks

**Comment by p00f** [comment] 2021-06-25 12:22
I get `TypeError: could not convert type int to gint required for parameter 1` when I press record after building from source

**Comment by SeaDve** [comment] 2021-06-25 12:25
Can i get the full traceback? thanks

**Comment by p00f** [comment] 2021-06-25 12:27
```
(python3:29565): Gdk-WARNING **: 17:57:24.960: Compositor doesn't support moving popups, relying on remapping
INFO:kooha.backend.recorder:is_show_pointer: True
INFO:kooha.backend.recorder:is_selection_mode: False
INFO:kooha.backend.screencast_portal:Session created
INFO:kooha.backend.screencast_portal:Sources selected
Traceback (most recent call last):
  File "/usr/local/share/kooha/kooha/backend/screencast_portal.py", line 83, in _on_start_response
    self.emit('ready', fd, node_id, stream_screen, self.is_selection_mode)
TypeError: could not convert type int to gint required for parameter 1
```

**Comment by SeaDve** [comment] 2021-06-25 12:29
that's weird, pygobect should handle converting it to gint

**Comment by SeaDve** [comment] 2021-06-25 12:31
you could possible use this already built package https://github.com/SeaDve/Kooha/suites/3075793315/artifacts/70121562 although you'll need flatpak some runtimes

**Comment by p00f** [comment] 2021-06-25 12:40
I get the same error (I did `flatpak install ~/Downloads/Kooha-dev.flatpak` and let flatpak install whatever it wanted)

**Comment by SeaDve** [comment] 2021-06-25 13:04
the value it may be emitting must be bigger than a gint could contain, ive never experience that issue.

Could you maybe replace line 83 in screencast_portal.py with 

`self.emit('ready', fd, 1, stream_screen, self.is_selection_mode)`

**Comment by p00f** [comment] 2021-06-25 13:28
Yes that worked!

**Comment by SeaDve** [comment] 2021-06-25 13:31
does recording work? That work around though is not really recommended, since node_id is needed by pipewire.

You could print the value of node_id by adding this line before self.emit...

`print(node_id)`

It would be helpful on debugging why it is causing type error etc.

**Comment by p00f** [comment] 2021-06-25 13:34
4294967295

**Comment by p00f** [comment] 2021-06-25 13:35
Yes, recording works

**Comment by SeaDve** [comment] 2021-06-25 13:35
thanks, that really a huge number, idk where that came from

**Comment by SeaDve** [comment] 2021-06-25 13:37
maybe this time replace print(node_id) with results, so i can check all the outputs from the portal

**Comment by p00f** [comment] 2021-06-25 13:47
`{'streams': [(4294967295, {'position': (0, 0), 'size': (1440, 900)})]}`

**Comment by SeaDve** [comment] 2021-06-25 13:48
thanks a lot. I'm really not sure why that number is that huge

**Comment by timsofteng** [comment] 2021-06-30 13:50
Unfortunately still doesn't work with sway.
Nixos unstable

**Comment by p00f** [comment] 2021-06-30 13:52
> Unfortunately still doesn't work with sway.
> Nixos unstable

Even after this:
> Could you maybe replace line 83 in screencast_portal.py with
> `self.emit('ready', fd, 1, stream_screen, self.is_selection_mode)`
?

**Comment by SeaDve** [comment] 2021-06-30 13:54
> Unfortunately still doesn't work with sway.
> Nixos unstable

which version. Nixos unstable seems to use the old 1.2.1

**Comment by timsofteng** [comment] 2021-06-30 14:09
> > Unfortunately still doesn't work with sway.
> > Nixos unstable
> 
> which version? Nixos unstable seems to use the old 1.2.1

yep, 1.2.1...

**Comment by SeaDve** [comment] 2021-06-30 14:10
that doesn't have sway support unfortunately. You'll have to use the version from main branch, through building from source or getting a package from github action.

**Comment by timsofteng** [comment] 2021-06-30 14:12
> that doesn't have sway support unfortunately. You'll have to use the version from main branch, through building from source or getting a package from github action.

got it.
I'll ping maintainers to update it.

BTW, why you didn't just make frontend for wf-recorder?
It works pretty good and doesn't require many dependencies.

**Comment by SeaDve** [comment] 2021-06-30 14:13
it seems to only work for wl-roots based compositors. It seems to won't work with other like mutter and kwin?

**Comment by timsofteng** [comment] 2021-06-30 14:16
> it seems to only work for wl-roots based compositors. It seems to won't work with other like mutter and kwin?

Hm... To be honest I dunno. I guessed it works.

**Comment by SeaDve** [comment] 2021-06-30 14:18
Well, according to the readme. Also, even it is possible, basing from wf-recorder, would probably remove certain features, as I would have less control to the recording, encoding in the pipeline

**Comment by timsofteng** [comment] 2021-06-30 14:21
> > Unfortunately still doesn't work with sway.
> > Nixos unstable
> 
> which version? Nixos unstable seems to use the old 1.2.1

hm... but according to repo 1.2.1 is a last release

**Comment by SeaDve** [comment] 2021-06-30 14:22
what do you mean last release?

**Comment by timsofteng** [comment] 2021-06-30 14:35
Oh. You mean latest commit... But version is 1.2.1. Finally got it.

**Comment by SeaDve** [comment] 2021-07-01 05:14
Update `self.emit('ready', fd, 1, stream_screen, self.is_selection_mode)` shouldn't be needed anymore :D

**Comment by p00f** [comment] 2021-07-01 05:25
Thanks, this works

**Comment by SeaDve** [comment] 2021-07-02 00:54
Feel free to close this, since everything that is needed to support on sway is now merged. You can open a new issue if there are bugs.

**Comment by asjur** [comment] 2021-07-06 10:44
I tried installing the flatpak listed above and it wouldn't work on my Sway install. I then tried to build from source and it had the same error.

When launching from terminal and clicking record, I was able to get the following message:
`(python3:3918): io.github.seadve.Kooha-WARNING **: 12:40:58.352: (screencast_portal.py, _on_create_session_response, 43) Failed to create session: 2`

When checking for dependencies I should have them all, or am I missing something?

```
~ ❯ pacman -Qs xdg-desktop-portal                                                                                                                                                                                                                                                                                                                                                  12:43:15
local/xdg-desktop-portal 1.8.1-1
    Desktop integration portals for sandboxed apps
local/xdg-desktop-portal-gtk 1.8.0-1
    A GTK+ backend for xdg-desktop-portal
local/xdg-desktop-portal-wlr 0.4.0-2
    xdg-desktop-portal backend for wlroots

**Comment by p00f** [comment] 2021-07-06 11:28
Are the portals running when you launch Kooha?

**Comment by asjur** [comment] 2021-07-06 11:31
> Are the portals running when you launch Kooha?

```systemctl --user status xdg-desktop-portal-wlr.service                                                   13:30:35
● xdg-desktop-portal-wlr.service - Portal service (wlroots implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-wlr.service; static)
     Active: active (running) since Tue 2021-07-06 13:30:35 CEST; 31s ago

**Comment by SeaDve** [comment] 2021-07-06 11:51
I think that must be causing the issue. I'm currently debugging it.

**Comment by asjur** [comment] 2021-07-06 11:57
Sorry for the spam but it seem adding the following to my configuration makes it at least work.
`exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway`

However it is not working properly. 

My issues:

- Confusing which screen is "highlighted", is the one with a overlay selected or the opposite?
- Attempting to use region does not work, or maybe it does in the recording but I wouldn't know. When attempting to click drag on the screen I want to record from the screen goes black with the cursor still visible. If I press escape it seems to cancel the whole process. Likely related to the region select.

**Comment by SeaDve** [comment] 2021-07-06 12:02
btw does normal recording works? Did you installed it from flatpak?

The area selector uses cairo, perhaps it isn't installed

**Comment by asjur** [comment] 2021-07-06 12:03
> btw does normal recording works? Did you installed it from flatpak?
> 
> The area selector uses cairo to render, perhaps it isn't installed

I installed from source, but flatpak had the same result.

Cairo is installed.
```
paru cairo                                                                                                                                                                                                                                                                                                                                                                     14:02:57
 1 extra/cairo 1.17.4-5 [0B 1.68MiB] [Installed]
    2D graphics library with support for multiple output devices
```

**Comment by SeaDve** [comment] 2021-07-06 12:08
> Confusing which screen is "highlighted", is the one with a overlay selected or the opposite?

This is current an issue too in #75
The one with overlay is what is selected.
It is a hard to fix issue because there is no explicit way for an app to determine which monitor is selected, because of wayland security stuff

may you show how it looks like, Its pretty hard to picture what is going black, maybe through a recording, thanks

**Comment by asjur** [comment] 2021-07-06 12:13
The recording works but it's impossible to tell what I am going to be recording.

https://streamable.com/hn84q8

**Comment by SeaDve** [comment] 2021-07-06 12:15
recording timer seems to be missing too. Everything with css, possibly the css isn't loading properly.

**Comment by asjur** [comment] 2021-07-06 12:15
The timer is there but it's white on white essentially. :D

**Comment by SeaDve** [comment] 2021-07-06 12:16
the timer is normally red

**Comment by SeaDve** [comment] 2021-07-10 03:50
@asjur I found out that non-compositing window managers cannot render transparent windows. Is sway non-compositing?

**Comment by p00f** [comment] 2021-07-10 03:58
All wayland WMs are compositing

**Comment by SeaDve** [comment] 2021-07-10 04:04
i might have used the wrong term

**Comment by SeaDve** [comment] 2021-07-10 04:09
or perhaps the display doesn't support alpha channels

**Comment by p00f** [comment] 2021-07-10 04:12
> Do you also get the opaque black background during area selection?

Yes

**Comment by faern** [comment] 2021-07-12 11:48
Sway surely can render semi-transparent windows. I for example use `slurp` to select regions to screenshot and that program is able to draw a semi-transparent gray overlay over my entire screen.

**Comment by SeaDve** [comment] 2021-07-16 11:34
I have rewritten it to use ngl renderer instead of cairo. You can test it through `rust` branch

**Comment by SeaDve** [comment] 2021-08-01 02:34
the fix had been merge to master. Thanks for participation!

**Comment by asjur** [comment] 2021-08-03 08:57
> the fix had been merge to master. Thanks for participation!

Hi, thanks for your work. 

I recompiled from latest master commit as of this comment and these are my findings:
The screen still goes black.
I see a selection however on the black screen.

**Comment by SeaDve** [comment] 2021-08-03 09:02
hi, thanks. It seems it changed nothing at all, I'll rewrite it probably again, to also fix some windowing bugs

**Comment by SeaDve** [comment] 2021-08-04 07:23
I put some useful information in the latest commit to help determine the root of the issue. It would be great to get the output of the logs ran with the bug occurring, thanks

**Comment by asjur** [comment] 2021-08-09 08:34
Hi, as of latest commit I cannot compile Kooha anymore.

/usr/bin/ld: /home/alex/Downloads/Kooha/builddir/target/release/deps/liblibadwaita-3d092696ec2cdcf4.rlib(libadwaita-3d092696ec2cdcf4.libadwaita.2o2ha7jy-cgu.12.rcgu.o): in function `<libadwaita::auto::application::Application as glib::types::StaticType>::static_type':
          libadwaita.2o2ha7jy-cgu.12:(.text._ZN86_$LT$libadwaita..auto..application..Application$u20$as$u20$glib..types..StaticType$GT$11static_type17h1a9688249ef12388E+0x2): undefined reference to `adw_application_get_type'
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: could not compile `kooha`

**Comment by SeaDve** [comment] 2021-08-09 08:48
you need the latest git version of libadwaita

**Comment by asjur** [comment] 2021-08-09 08:58
Thanks, I was able to compile it. Seems like there's been a regression. When I select the area and the application should start recording, it instead freezes and never starts recording, as a result the terminal is not showing any output as well and I have to kill it manually.

I did another test, set delay to 5 seconds and video format to WebM, chose region (with the black screen bug) and it starts counting down. It reaches 1 and freezes as well. The only thing visible in the terminal is the following which showed before clicking record.
kooha:38784): Gdk-WARNING **: 10:55:07.977: Compositor doesn't support moving popups, relying on remapping

**Comment by SeaDve** [comment] 2021-08-09 09:10
Does it also crashes on normal mode?

**Comment by asjur** [comment] 2021-08-09 09:15
Yes it also crashes on normal mode.

No there is no such thing. This is the entirety of my terminal.

~ ❯ kooha                                                                                                                                                                                                 11:14:59

(kooha:40175): Gtk-WARNING **: 11:15:01.791: Unknown key gtk-button-images in /home/alex/.config/gtk-4.0/settings.ini

(kooha:40175): Gtk-WARNING **: 11:15:01.791: Unknown key gtk-menu-images in /home/alex/.config/gtk-4.0/settings.ini

(kooha:40175): Gtk-WARNING **: 11:15:01.791: Unknown key gtk-toolbar-style in /home/alex/.config/gtk-4.0/settings.ini
^C
~ 11s ❯

**Comment by SeaDve** [comment] 2021-08-09 09:16
run it with `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 kooha`
hehe so much variables

**Comment by asjur** [comment] 2021-08-09 09:18
~ ❯ RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 kooha                                                                                                                              11:17:38
 INFO  kooha::application > Kooha (io.github.seadve.Kooha)
 INFO  kooha::application > Version: 1.2.1 ()
 INFO  kooha::application > Datadir: /usr/local/share/kooha

(kooha:40407): Gtk-WARNING **: 11:17:39.866: Unknown key gtk-button-images in /home/alex/.config/gtk-4.0/settings.ini

(kooha:40407): Gtk-WARNING **: 11:17:39.866: Unknown key gtk-menu-images in /home/alex/.config/gtk-4.0/settings.ini

(kooha:40407): Gtk-WARNING **: 11:17:39.866: Unknown key gtk-toolbar-style in /home/alex/.config/gtk-4.0/settings.ini
 DEBUG kooha::backend::recorder > is_show_pointer: true
 DEBUG kooha::backend::recorder > is_selection_mode: false
 INFO  kooha::backend::screencast_portal > ScreenCastProxy created
 INFO  kooha::backend::screencast_portal > Session created
 INFO  kooha::backend::screencast_portal > Select sources window showed
 INFO  kooha::backend::screencast_portal > Screencast session started
 INFO  kooha::backend::screencast_portal > Ready for pipewire stream
 DEBUG kooha::backend::recorder          > PipelineBuilder { is_record_speaker: false, is_record_mic: false, framerate: 30, file_path: "/home/alex/Videos/Kooha 08-09-2021 11:17:43.webm", fd: 20, streams: [Stream { pipewire_node_id: 4294967295, position: Some((0, 0)), size: Some((1920, 1080)) }], speaker_source: Some("alsa_output.pci-0000_07_00.6.HiFi__hw_Generic_1__sink.monitor"), mic_source: Some("alsa_input.pci-0000_07_00.6.HiFi__hw_Generic_1__source"), coordinates: None, actual_screen: None }
 DEBUG kooha::backend::pipeline_builder  > is_use_vaapi: false
 DEBUG kooha::backend::pipeline_builder  > pipeline_string: queue name=queue0 ! videorate ! video/x-raw, framerate=30/1 ! videoconvert chroma-mode=GST_VIDEO_CHROMA_MODE_NONE dither=GST_VIDEO_DITHER_NONE matrix-mode=GST_VIDEO_MATRIX_MODE_OUTPUT_ONLY n-threads=16 ! queue ! vp8enc max_quantizer=17 cpu-used=16 cq_level=13 deadline=1 static-threshold=100 keyframe-mode=disabled buffer-size=20000 threads=16 ! queue ! webmmux name=mux ! filesink location="/home/alex/Videos/Kooha 08-09-2021 11:17:43.webm" pipewiresrc fd=20 path=4294967295 do-timestamp=true keepalive-time=1000 resend-last=true ! video/x-raw, max-framerate=30/1 ! queue0.
[I][07498.791375][      pipewire.c:  559 pw_init()] version 0.3.33
[I][07504.500216][          conf.c:  271 conf_load()] config 0x5562f1d90ba0: loading config '/usr/share/pipewire/client.conf'
[I][07504.500335][       context.c:  337 pw_context_new()] context 0x5562f1d71e70: parsed context.properties section
[I][07504.502076][       context.c:  427 pw_context_new()] context 0x5562f1d71e70: parsed 2 context.spa-libs items
[I][07504.502788][          conf.c:  340 load_module()] config 0x5562f1d71e70: loaded module libpipewire-module-protocol-native
[I][07504.503395][          conf.c:  340 load_module()] config 0x5562f1d71e70: loaded module libpipewire-module-client-node
[I][07504.503660][          conf.c:  340 load_module()] config 0x5562f1d71e70: loaded module libpipewire-module-client-device
[I][07504.503946][          conf.c:  340 load_module()] config 0x5562f1d71e70: loaded module libpipewire-module-adapter
[I][07504.504488][          conf.c:  340 load_module()] config 0x5562f1d71e70: loaded module libpipewire-module-metadata
[I][07504.504983][          conf.c:  340 load_module()] config 0x5562f1d71e70: loaded module libpipewire-module-session-manager
[I][07504.504999][       context.c:  431 pw_context_new()] context 0x5562f1d71e70: parsed 6 context.modules items
[I][07504.505010][       context.c:  436 pw_context_new()] context 0x5562f1d71e70: parsed 0 context.objects items
[I][07504.505018][       context.c:  439 pw_context_new()] context 0x5562f1d71e70: parsed 0 context.exec items
[I][07504.505076][       context.c:  230 context_set_freewheel()] context 0x5562f1d71e70: exit freewheel
[I][07504.505110][       context.c:  234 context_set_freewheel()] context 0x5562f1d71e70: freewheel error:Operation not supported
[I][07504.505125][ impl-metadata.c:  196 impl_set_property()] metadata 0x5562f1d93f00: add id:0 key:log.level type: value:0
[I][07504.505136][ impl-metadata.c:  196 impl_set_property()] metadata 0x5562f1d93f00: add id:0 key:clock.min-quantum type: value:32
[I][07504.505147][ impl-metadata.c:  196 impl_set_property()] metadata 0x5562f1d93f00: add id:0 key:clock.max-quantum type: value:8192
[I][07504.505156][ impl-metadata.c:  196 impl_set_property()] metadata 0x5562f1d93f00: add id:0 key:clock.force-quantum type: value:0
[I][07504.505163][ impl-metadata.c:  196 impl_set_property()] metadata 0x5562f1d93f00: add id:0 key:clock.force-rate type: value:0
0:00:09.237030260 40407 0x7f8d042a25e0 FIXME                default gstutils.c:4025:gst_pad_create_stream_id_internal:<pipewiresrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
[E][07504.507291][        stream.c:  362 stream_set_state()] stream 0x5562f1dcb350: error wrong resource type/version
0:00:09.238646614 40407 0x5562f1c6a730 WARN             pipewiresrc gstpipewiresrc.c:529:on_state_changed:<pipewiresrc0> error: stream error: wrong resource type/version
[W][07504.507486][gstpipewirecore.:   42 on_core_error()] error id:2 seq:2 res:-71 (Protocol error): wrong resource type/version
[W][07504.507531][     impl-node.c:  383 suspend_node()] node 0x7f8ce8009a70: error unset format input: Input/output error
[I][07504.507552][     impl-node.c:  353 node_update_state()] (kooha-0) creating -> suspended
[W][07504.507577][gstpipewirecore.:   42 on_core_error()] error id:0 seq:3 res:-2 (No such file or directory): unknown resource 2 op:2
[W][07504.507594][gstpipewirecore.:   42 on_core_error()] error id:0 seq:4 res:-2 (No such file or directory): unknown resource 2 op:3
^C
~ 13s ❯

**Comment by SeaDve** [comment] 2021-08-09 09:21
I think it may be caused by this https://github.com/SeaDve/Kooha/blob/6d21a19ebd07648b476abb352dab092e7009597b/src/backend/screencast_portal.rs#L116 Try settings let multiple = false;

**Comment by SeaDve** [comment] 2021-08-09 09:26
Did your pipewire version changed since the last time it works?

**Comment by asjur** [comment] 2021-08-09 09:31
I made the change you mentioned and recompiled with no difference. I did a reinstall of pipewire and restarted, it no longer crashes (perhaps there was an upgrade).

I now get the following output in terminal, I'm including debug in the event that it is useful.

RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 kooha                                                                                                                                                                                                                                                                                                       11:29:14
 INFO  kooha::application > Kooha (io.github.seadve.Kooha)
 INFO  kooha::application > Version: 1.2.1 ()
 INFO  kooha::application > Datadir: /usr/local/share/kooha

(kooha:2189): Gtk-WARNING **: 11:29:15.259: Unknown key gtk-button-images in /home/alex/.config/gtk-4.0/settings.ini

(kooha:2189): Gtk-WARNING **: 11:29:15.259: Unknown key gtk-menu-images in /home/alex/.config/gtk-4.0/settings.ini

(kooha:2189): Gtk-WARNING **: 11:29:15.259: Unknown key gtk-toolbar-style in /home/alex/.config/gtk-4.0/settings.ini
 DEBUG kooha::backend::recorder > is_show_pointer: true
 DEBUG kooha::backend::recorder > is_selection_mode: true
 INFO  kooha::backend::screencast_portal > ScreenCastProxy created
 INFO  kooha::backend::screencast_portal > Session created
 INFO  kooha::backend::screencast_portal > Select sources window showed
 INFO  kooha::backend::screencast_portal > Screencast session started
 INFO  kooha::backend::screencast_portal > Ready for pipewire stream
 INFO  kooha::widgets::area_selector     > is_display_composited: true
 INFO  kooha::widgets::area_selector     > is_display_rgba: true
 WARN  kooha::widgets::area_selector     > Failed to set raise active window to true: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell was not provided by any .service files
 INFO  kooha::backend::recorder          > Captured coordinates
 WARN  kooha::widgets::area_selector     > Failed to set raise active window to false: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell was not provided by any .service files
 DEBUG kooha::backend::recorder          > PipelineBuilder { is_record_speaker: false, is_record_mic: false, framerate: 30, file_path: "/home/alex/Videos/Kooha 08-09-2021 11:29:18.webm", fd: 20, streams: [Stream { pipewire_node_id: 4294967295, position: Some((0, 0)), size: Some((3440, 1440)) }], speaker_source: Some("alsa_output.pci-0000_07_00.6.HiFi__hw_Generic_1__sink.monitor"), mic_source: Some("alsa_input.pci-0000_07_00.6.HiFi__hw_Generic_1__source"), coordinates: Some(Rectangle { x: 1182.7421875, y: 503.39453125, width: 1231.0234375, height: 565.9921875 }), actual_screen: Some(Screen { width: 3440, height: 1440 }) }
 DEBUG kooha::backend::pipeline_builder  > is_use_vaapi: false
 DEBUG kooha::backend::pipeline_builder  > pipeline_string: queue name=queue0 ! videorate ! video/x-raw, framerate=30/1 ! videoscale ! video/x-raw, width=3440, height=1440 ! videocrop top=502 left=1182 right=1026 bottom=370 ! videoconvert chroma-mode=GST_VIDEO_CHROMA_MODE_NONE dither=GST_VIDEO_DITHER_NONE matrix-mode=GST_VIDEO_MATRIX_MODE_OUTPUT_ONLY n-threads=16 ! queue ! vp8enc max_quantizer=17 cpu-used=16 cq_level=13 deadline=1 static-threshold=100 keyframe-mode=disabled buffer-size=20000 threads=16 ! queue ! webmmux name=mux ! filesink location="/home/alex/Videos/Kooha 08-09-2021 11:29:18.webm" pipewiresrc fd=20 path=4294967295 do-timestamp=true keepalive-time=1000 resend-last=true ! video/x-raw, max-framerate=30/1 ! queue0.
[I][00041.109866][      pipewire.c:  559 pw_init()] version 0.3.33
[I][00046.117377][          conf.c:  271 conf_load()] config 0x55bf96a1d2d0: loading config '/usr/share/pipewire/client.conf'
[I][00046.117455][       context.c:  337 pw_context_new()] context 0x55bf96a6b4d0: parsed context.properties section
[I][00046.118385][       context.c:  427 pw_context_new()] context 0x55bf96a6b4d0: parsed 2 context.spa-libs items
[I][00046.118750][          conf.c:  340 load_module()] config 0x55bf96a6b4d0: loaded module libpipewire-module-protocol-native
[I][00046.119105][          conf.c:  340 load_module()] config 0x55bf96a6b4d0: loaded module libpipewire-module-client-node
[I][00046.119330][          conf.c:  340 load_module()] config 0x55bf96a6b4d0: loaded module libpipewire-module-client-device
[I][00046.119600][          conf.c:  340 load_module()] config 0x55bf96a6b4d0: loaded module libpipewire-module-adapter
[I][00046.119855][          conf.c:  340 load_module()] config 0x55bf96a6b4d0: loaded module libpipewire-module-metadata
[I][00046.120098][          conf.c:  340 load_module()] config 0x55bf96a6b4d0: loaded module libpipewire-module-session-manager
[I][00046.120125][       context.c:  431 pw_context_new()] context 0x55bf96a6b4d0: parsed 6 context.modules items
[I][00046.120133][       context.c:  436 pw_context_new()] context 0x55bf96a6b4d0: parsed 0 context.objects items
[I][00046.120140][       context.c:  439 pw_context_new()] context 0x55bf96a6b4d0: parsed 0 context.exec items
[I][00046.120186][       context.c:  230 context_set_freewheel()] context 0x55bf96a6b4d0: exit freewheel
[I][00046.120213][       context.c:  234 context_set_freewheel()] context 0x55bf96a6b4d0: freewheel error:Operation not supported
[I][00046.120225][ impl-metadata.c:  196 impl_set_property()] metadata 0x55bf96b95c20: add id:0 key:log.level type: value:0
[I][00046.120236][ impl-metadata.c:  196 impl_set_property()] metadata 0x55bf96b95c20: add id:0 key:clock.min-quantum type: value:32
[I][00046.120245][ impl-metadata.c:  196 impl_set_property()] metadata 0x55bf96b95c20: add id:0 key:clock.max-quantum type: value:8192
[I][00046.120255][ impl-metadata.c:  196 impl_set_property()] metadata 0x55bf96b95c20: add id:0 key:clock.force-quantum type: value:0
[I][00046.120265][ impl-metadata.c:  196 impl_set_property()] metadata 0x55bf96b95c20: add id:0 key:clock.force-rate type: value:0
0:00:09.009306737  2189 0x7fe2a422df00 FIXME                default gstutils.c:4025:gst_pad_create_stream_id_internal:<pipewiresrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
[I][00046.127868][     impl-node.c:  353 node_update_state()] (kooha-0) creating -> running
 INFO  kooha::backend::recorder          > Pipeline state set from Null -> Ready
 INFO  kooha::backend::recorder          > Pipeline state set from Ready -> Paused
0:00:09.076962049  2189 0x7fe2a421a980 FIXME               basesink gstbasesink.c:3384:gst_base_sink_default_event:<filesink0> stream-start event without group-id. Consider implementing group-id handling in the upstream elements
 INFO  kooha::backend::recorder          > Pipeline state set from Paused -> Playing
 INFO  kooha::backend::recorder          > Sending eos event to pipeline
[I][00052.631109][     impl-node.c:  353 node_update_state()] (kooha-0) running -> idle
[I][00052.636645][     impl-node.c:  353 node_update_state()] (kooha-0) idle -> suspended
[I][00052.638621][     impl-node.c: 1718 pw_impl_node_destroy()] (kooha-0) destroy
 INFO  kooha::backend::screencast_portal > Session closed
 INFO  kooha::backend::recorder          > Eos signal received from record bus

**Comment by SeaDve** [comment] 2021-08-09 09:37
Thanks! So the only problem now is the blackscreen?

**Comment by SeaDve** [comment] 2021-08-09 09:38
Everything seems good with the logs, I'm still not sure why and what is causing the black window on sway

**Comment by asjur** [comment] 2021-08-09 09:58
Correct, the black screen is the only problem.

**Comment by SeaDve** [comment] 2021-08-09 10:18
Possible, I had tried it, but doesn't work on gnome

**Comment by SeaDve** [comment] 2021-08-09 10:19
I'll open a separate issue, since this is getting very long

**Comment by SeaDve** [comment] 2021-08-09 10:19
And it seems the only issue left on sway

**Closed** 2021-08-09 10:19 UTC
Labels: enhancement
