### ISSUE TITLE
Start recording fails

### ISSUE THREAD

**Issue by alfonsonv** [SeaDve/Kooha#148] opened 2022-01-12 16:06 UTC
**System Info**
- Kooha version (2.0.1)
- Distro information and version (Ubuntu 21.10 x86_64)
- Desktop Environment information and version (GNOME 40.5)
- Display Server (Xorg)
- Flatpak io.github.seadve.Kooha

**Describe the bug**
Can´t start recording, after a few seconds an error message is shown with the message:
Stream error: wrong resource type/version.

**To Reproduce**
1. Start the app
2. Click on 'Record'
3. Select entire screen and monitor.
4. Click in share
5. After a few seconds appears the error message: Stream error: wrong resource type/version.

**Expected behavior**
That start recording the screen.

**Screenshots**
None.

**Additional context**
 INFO  kooha::application > Kooha (io.github.seadve.Kooha)
 INFO  kooha::application > Version: 2.0.1 ()
 INFO  kooha::application > Datadir: /app/share/kooha
 DEBUG kooha::backend::recorder > is_show_pointer: true
 DEBUG kooha::backend::recorder > is_selection_mode: false
 INFO  kooha::backend::screencast_portal > ScreenCastProxy created
 DEBUG kooha::backend::screencast_portal > available_cursor_modes: BitFlags<CursorMode>(0b111, Hidden | Embedded | Metadata)
 DEBUG kooha::backend::screencast_portal > available_source_types: BitFlags<SourceType>(0b11, Monitor | Window)
 INFO  kooha::backend::screencast_portal > Session created
 INFO  kooha::backend::screencast_portal > Select sources window showed
 INFO  kooha::backend::screencast_portal > Screencast session started
 INFO  kooha::backend::screencast_portal > Ready for pipewire stream
 DEBUG kooha::backend::recorder          > pulse_server_version: pulseaudio version 15.0
 DEBUG kooha::backend::recorder          > PipelineBuilder { is_record_speaker: true, is_record_mic: true, framerate: 30, file_path: "/home/alfonso/Vídeos/pantalla/Kooha-01-12-2022-09-02-02.mp4", fd: 31, streams: [Stream { pipewire_node_id: 41, position: Some((0, 0)), size: Some((1920, 1080)) }], speaker_source: Some("alsa_output.pci-0000_08_00.1.hdmi-stereo-extra1.monitor"), mic_source: Some("alsa_input.usb-C-Media_Electronics_Inc._USB_PnP_Sound_Device-00.mono-fallback"), coordinates: None, actual_screen: None }
 DEBUG kooha::backend::pipeline_builder  > is_use_vaapi: false
 DEBUG kooha::backend::pipeline_builder  > pipeline_string: queue name=queue0 ! videorate ! video/x-raw, framerate=30/1 ! videoconvert chroma-mode=GST_VIDEO_CHROMA_MODE_NONE dither=GST_VIDEO_DITHER_NONE matrix-mode=GST_VIDEO_MATRIX_MODE_OUTPUT_ONLY n-threads=4 ! queue ! x264enc qp-max=17 speed-preset=superfast threads=4 ! video/x-h264, profile=baseline ! queue ! mp4mux name=mux ! filesink name=filesink location="/home/alfonso/Vídeos/pantalla/Kooha-01-12-2022-09-02-02.mp4" pipewiresrc fd=31 path=41 do-timestamp=true keepalive-time=1000 resend-last=true ! video/x-raw, max-framerate=30/1 ! queue0. pulsesrc device="alsa_output.pci-0000_08_00.1.hdmi-stereo-extra1.monitor" ! queue ! audiomixer name=mix ! opusenc ! queue ! mux. pulsesrc device="alsa_input.usb-C-Media_Electronics_Inc._USB_PnP_Sound_Device-00.mono-fallback" ! queue ! mix.
[I][03164.192210][      pipewire.c:  571 pw_init()] version 0.3.35
[I][03164.205701][          conf.c:  326 conf_load()] config 0x561a6749cb70: loading config '/usr/share/pipewire/client.conf'
[I][03164.206021][       context.c:  384 pw_context_new()] context 0x561a6747b060: parsed context.properties section
[I][03164.206664][       context.c:  478 pw_context_new()] context 0x561a6747b060: parsed 2 context.spa-libs items
[I][03164.207070][          conf.c:  419 load_module()] config 0x561a6747b060: loaded module libpipewire-module-protocol-native
[I][03164.207520][          conf.c:  419 load_module()] config 0x561a6747b060: loaded module libpipewire-module-client-node
[I][03164.207795][          conf.c:  419 load_module()] config 0x561a6747b060: loaded module libpipewire-module-client-device
[I][03164.208012][          conf.c:  419 load_module()] config 0x561a6747b060: loaded module libpipewire-module-adapter
[I][03164.208225][          conf.c:  419 load_module()] config 0x561a6747b060: loaded module libpipewire-module-metadata
[I][03164.208466][          conf.c:  419 load_module()] config 0x561a6747b060: loaded module libpipewire-module-session-manager
[I][03164.208490][       context.c:  482 pw_context_new()] context 0x561a6747b060: parsed 6 context.modules items
[I][03164.208514][       context.c:  487 pw_context_new()] context 0x561a6747b060: parsed 0 context.objects items
[I][03164.208531][       context.c:  490 pw_context_new()] context 0x561a6747b060: parsed 0 context.exec items
[I][03164.208596][       context.c:  244 context_set_freewheel()] context 0x561a6747b060: exit freewheel
[I][03164.208641][       context.c:  248 context_set_freewheel()] context 0x561a6747b060: freewheel error:La operación no está soportada
[I][03164.208672][ impl-metadata.c:  196 impl_set_property()] metadata 0x561a676400c0: add id:0 key:log.level type: value:0
[I][03164.208691][ impl-metadata.c:  196 impl_set_property()] metadata 0x561a676400c0: add id:0 key:clock.min-quantum type: value:32
[I][03164.208708][ impl-metadata.c:  196 impl_set_property()] metadata 0x561a676400c0: add id:0 key:clock.max-quantum type: value:8192
[I][03164.208725][ impl-metadata.c:  196 impl_set_property()] metadata 0x561a676400c0: add id:0 key:clock.force-quantum type: value:0
[I][03164.208741][ impl-metadata.c:  196 impl_set_property()] metadata 0x561a676400c0: add id:0 key:clock.force-rate type: value:0
0:00:49.299312975     2 0x7f96cc3ceb00 WARN              aggregator gstaggregator.c:2050:gst_aggregator_query_latency_unlocked:<mix> Latency query failed
0:00:49.299328374     2 0x7f96cc3ceb00 WARN              aggregator gstaggregator.c:2050:gst_aggregator_query_latency_unlocked:<mux> Latency query failed
0:00:49.299644575     2 0x7f96cc4c1120 WARN              aggregator gstaggregator.c:2050:gst_aggregator_query_latency_unlocked:<mix> Latency query failed
0:00:49.299902336     2 0x7f96cc4c7ea0 FIXME                default gstutils.c:4025:gst_pad_create_stream_id_internal:<pipewiresrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:49.299927223     2 0x7f96cc4c1300 FIXME                default gstutils.c:4025:gst_pad_create_stream_id_internal:<pulsesrc1:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:49.299987906     2 0x7f96cc4c1120 WARN              aggregator gstaggregator.c:2050:gst_aggregator_query_latency_unlocked:<mix> Latency query failed
0:00:49.299905071     2 0x7f96cc4bcc00 FIXME                default gstutils.c:4025:gst_pad_create_stream_id_internal:<pulsesrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:49.300600561     2 0x7f96cc4c1120 WARN              aggregator gstaggregator.c:2050:gst_aggregator_query_latency_unlocked:<mix> Latency query failed
[E][03164.213460][        stream.c:  365 stream_set_state()] stream 0x561a676545f0: error wrong resource type/version
0:00:49.303636714     2 0x7f96b0001e30 WARN             pipewiresrc gstpipewiresrc.c:529:on_state_changed:<pipewiresrc0> error: stream error: wrong resource type/version
[W][03164.213565][gstpipewirecore.:   42 on_core_error()] error id:2 seq:2 res:-71 (Error de protocolo): wrong resource type/version
[W][03164.213587][     impl-node.c:  388 suspend_node()] node 0x7f9668007d00: error unset format input: Error de entrada/salida
[I][03164.213597][     impl-node.c:  358 node_update_state()] (kooha-0) creating -> suspended
[W][03164.213610][gstpipewirecore.:   42 on_core_error()] error id:0 seq:3 res:-2 (No existe el fichero o el directorio): unknown resource 2 op:2
[W][03164.213619][gstpipewirecore.:   42 on_core_error()] error id:0 seq:4 res:-2 (No existe el fichero o el directorio): unknown resource 2 op:3
 ERROR kooha::backend::recorder::imp     > Failed to set pipeline state to Playing: StateChangeError
0:01:19.303212300     2 0x7f96cc4c7ea0 WARN                 basesrc gstbasesrc.c:3127:gst_base_src_loop:<pipewiresrc0> error: Internal data stream error.
0:01:19.303247285     2 0x7f96cc4c7ea0 WARN                 basesrc gstbasesrc.c:3127:gst_base_src_loop:<pipewiresrc0> error: streaming stopped, reason not-negotiated (-4)
 INFO  kooha::backend::recorder          > Pipeline state set from Null -> Ready
0:01:19.305325047     2 0x561a6650a000 WARN               structure gststructure.c:2069:priv_gst_structure_append_to_gstring: No value transform to serialize field 'gerror' of type 'GError'
 ERROR kooha::backend::recorder          > Error from record bus: Error { domain: gst-resource-error-quark, code: 1, message: "stream error: wrong resource type/version" } (debug Error(Message { ptr: 0x7f9678001c80, type: "error", seqnum: 133, src: Some("pipewiresrc0"), structure: Some(GstMessageError, gerror=(GError)NULL, debug=(string)"../src/gst/gstpipewiresrc.c\(529\):\ on_state_changed\ \(\):\ /GstPipeline:pipeline0/GstPipeWireSrc:pipewiresrc0";) }))
[I][03194.215987][     impl-node.c: 1736 pw_impl_node_destroy()] (kooha-0) destroy
 INFO  kooha::backend::screencast_portal > Session closed

**Comment by SeaDve** [comment] 2022-01-14 00:13
seems duplicate of #120 or #135. Please close this if you it is

**Closed** 2022-01-14 00:45 UTC
