### ISSUE TITLE
Kooha 

### ISSUE THREAD

**Issue by bobster007** [SeaDve/Kooha#226] opened 2023-03-05 20:18 UTC
**System Info**

**Describe the bug**
Kooha reproduces the colors wrongly. It seems as if red and blue were swapped. Attached a screenshot of the selection screen. The final video has the same problem

**To Reproduce**
1. Start a new video grab. Choose a screen with content in color. Compare the original colors with the once in Kooha window. You can also record the video and compare with the original.

**Expected behavior**
I'd expect the colors to be the same

**Screenshots**
![Kooha color problem](https://user-images.githubusercontent.com/52310913/222983618-9bf43a26-37f8-4ce0-a0f4-9c872165b3dc.png)

**Additional context**
If applicable, please attach the logs from running Kooha in the
terminal with the following environment variables: `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3`
(e.g., `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 flatpak run io.github.seadve.Kooha`).

**Comment by TheTrio** [comment] 2023-03-06 22:14
Having this issue as well

**Comment by denielt** [comment] 2023-03-07 22:45
damn, I was going to open an issue about this right now! I just installed some weeks ago to record my screen to make blender tutorials for youtube videos, but Kooha videos seems way darker whe compared to simplescreen, here is my screen normally: 

![image](https://user-images.githubusercontent.com/48871492/223570637-6a542b19-4910-4b96-bfa6-b9d5a356a057.png)

now, this is my screen with kooha:

![image](https://user-images.githubusercontent.com/48871492/223570837-9cfa81a7-5f86-4f6b-bb70-bfde7ef863c2.png)

it may not seem too much difference, but if you try to alt tab between the two images fast you'll see a huge diference in the contrast. now the problem gets even worse when I upload the file on youtube:

![image](https://user-images.githubusercontent.com/48871492/223571076-9f78d022-c549-40fd-8a3b-f886278fc493.png)

while I have absolutely no problems when I try to capture my screen directly from ffmpeg or simplescreenrecorder

**Comment by TheTrio** [comment] 2023-03-09 10:06
Looks like this might be a KDE issue - [Wayland: Red and blue channels are swapped when screencasting in certain applications](https://bugs.kde.org/show_bug.cgi?id=466655)

**Comment by denielt** [comment] 2023-03-16 01:36
> Looks like this might be a KDE issue - [Wayland: Red and blue channels are swapped when screencasting in certain applications](https://bugs.kde.org/show_bug.cgi?id=466655)

This is kinda strange, I have this problem while using gnome, when I try to use simplescreen which is a Qt application, no problems.

**Comment by TheTrio** [comment] 2023-03-18 10:49
I'm not exactly sure, but for me, the problem is fixed as of KDE 5.27.3

**Comment by luzpaz** [comment] 2023-06-24 00:42
Can this ticket be renamed to accurately reflect the issue it's reporting? TIA!

**Comment by bobster007** [comment] 2023-06-26 07:56
It was a KDE/Plasma issue. Newer versions of Plasma solved it.

**Closed** 2023-06-26 07:55 UTC
