### ISSUE TITLE
Cursor does not show when option is selected

### ISSUE THREAD

**Issue by danastasio** [SeaDve/Kooha#147] opened 2022-01-11 21:11 UTC
**System Info**
- **Kooha version**: 2.0.1
- **Distro information and version**: Fedora Workstation release 35 (Thirty Five)
- **Desktop Environment information and version**: GNOME 41.2
- **Display Server**: X11
- **Flatpak**? Yes

**Describe the bug**
When selecting the option to show the cursor, the cursor does not show

**To Reproduce**
1. Open Kooha
2. Click on the mouse icon
3. Click record
4. Record something
5. Click finish
6. Open the video
7. Wiggle the mouse around
8. View the recording produced by Kooha
9. There is no mouse

**Expected behavior**
The mouse should appear in step 8

**Screenshots**
n/a

**Additional context**
https://pastebin.com/9DFF3Mk9

**Comment by SeaDve** [comment] 2022-01-28 15:02
see #56 too if it is related, or the same issue?

**Comment by THEBATEZIOPARKER** [comment] 2022-01-28 15:24
Yep, Issue #144 is NOT the Same Issue.
Issue #56 Is Same Issue.

**Comment by SeaDve** [comment] 2022-08-15 03:20
Closing this as duplicate of #56

**Closed by SeaDve** 2022-08-15 03:20 UTC
