### ISSUE TITLE
Kooha 2.0.x freezes in Ubuntu 21.10 and derivatives (Pop 21.10)

### ISSUE THREAD

**Issue by spxak1** [SeaDve/Kooha#143] opened 2021-12-15 11:25 UTC
This is not a new issue, Kooha has not being working on Ubuntu after the 2.0.0 update (ver 1.x.x works but how do we install that instead).

I am surprised there are no reports of this here, and I couln'd find my bug report for Ubuntu 21.04 and derivatives.

Is there a solution or update to this?

I'm on Pop 21.10 and it has the same behaviour as Ubuntu 21.10. Fresh install makes no difference.

Thank you.

**Comment by maks** [comment] 2021-12-16 00:42
I had this issue on my ubuntu 21.10 until I moved over to the upstream version of pipewire. Kooha 2.0.1 now seems to work for me without freezing.

**Comment by maks** [comment] 2021-12-16 00:48
I think this is a duplicate of #120 and the comment there a[bout switching to upstream version of pipewire](https://github.com/SeaDve/Kooha/issues/120#issuecomment-948085087) fixing the issue is what fixed it for me too.

**Comment by SeaDve** [comment] 2021-12-16 01:08
Thanks! I'll close this issue then

**Comment by spxak1** [comment] 2021-12-16 01:08
> I think this is a duplicate of #120 and the comment there a[bout switching to upstream version of pipewire](https://github.com/SeaDve/Kooha/issues/120#issuecomment-948085087) fixing the issue is what fixed it for me too.

It is (same person). But installing pipewire on Ubuntu, while trivial, causes other regressions. It's not a fix, but a workaround.

**Closed by SeaDve** 2021-12-16 01:08 UTC

**Comment by SeaDve** [comment] 2021-12-16 01:10
Kooha needs pipewire too work

**Comment by spxak1** [comment] 2021-12-16 01:25
Thanks. 

For what it's worth, installing upstream pipewire in Pop 21.10 and enable the various services, and rebooting (for good measure) makes no difference. Kooha still hangs.

But I see this has caused some fatigue, so I guess I will have to stop asking. 

Thank you though.

**Comment by maks** [comment] 2021-12-16 01:35
@spxak1 my comment wasn't to stop you asking, it's just that as a open source maintainer myself, I know it's much easier to track the same problem in a single github issue versus having duplicates, so I wasn't suggesting you stop commenting, just to do it in issue 120 which has more information about it and predates this one.

**Comment by spxak1** [comment] 2021-12-16 17:03
Sorry, I didn't mean you were in any way on the wrong. 

I have 24 computers with PopOS 21.04 updating to 21.10 this weekend and was hoping to be able to use kooha as it's by far the best tools for our students to capture their screens when presenting.

My test box was able to use 1.x.x only in 21.04 and while it worked with the ppa pipewire, updating and maintaining 24 laptops with an extra ppa is (or can be) a pain.

Now my test box upgraded to 21.10 (I had removed the ppa piperwire) hoping ubuntu would have updated their pipewire, they haven't. So I'm back to square one. That's the fatigue. Mine mostly and since I'm bugging you, Pop and Ubuntu devs, to no effect, theirs too.

No I install the ppa pipewire on my test box, and kooha still doesn't work. I do a fresh 21.10 install, install the ppa, kooha works.  Back to the updated version, I remove Kooha, remove the ppa, restore default pipewire (as the other 24 computers will be), install kooha 1.x.x, now it doesn't work either. Fatigue. 

Sorry for venting, it's not your problem or fault. Just getting tired. 

Back from the start I guess.
