### ISSUE TITLE
when I want to record, I don't want to start

### ISSUE THREAD

**Issue by dandidwi** [SeaDve/Kooha#172] opened 2022-07-23 13:59 UTC
-Kooha version 2.0.1
-Distro Fedora 36 Spin Kde Plasma
-Wayland Display Server
-Flatpak

Can't start recording.
You can see in the following video
https://youtube.com/shorts/9uZ8aCDSC9w

**Comment by SeaDve** [comment] 2022-07-23 14:03
May you show the logs by running Kooha with `flatpak run io.github.seadve.Kooha`?

**Comment by 1011001-p** [comment] 2022-07-31 20:54
Hey I'm getting the same symptom. When I ran Kooha from the terminal and when I press record I get the following error as a log:
`(kooha:2): Gdk-WARNING **: 17:53:33.320: Server is missing xdg_foreign support`
Hope this helps

**Comment by SeaDve** [comment] 2022-08-15 03:16
Duplicate of #60

**Closed by SeaDve** 2022-08-15 03:16 UTC
