### ISSUE TITLE
Not running on Arcolinux-qtile

### ISSUE THREAD

**Issue by bjnobre** [SeaDve/Kooha#251] opened 2023-09-08 14:46 UTC
**Affected version**

- io.github.seadve.Kooha 2.2.3
- Flatpak: false
- Experimental: false

- Distribution: <unknown>
- Desktop Session: qtile
- Display Server: x11

- GTK 4.12.1
- Libadwaita 1.3.5
- GStreamer 1.22.5
- Pipewire 0.3.79

If there are other relevant version information, please include them here.

Failed to start recording

Caused by:
    0: Check out <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> for help.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Failed to call `CreateSession` with parameters: Variant { ptr: 0x559124520a30, type: VariantTy { inner: "(a{sv})" }, value: "({'handle_token': <'kooha_3'>, 'session_handle_token': <'kooha_2'>},)" }
    4: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

**Bug summary**

uname -r output:
6.4.12-arch1-1

qtile version:
0.22.1

**Comment by VicMCA** [comment] 2023-09-26 14:00
I think my issue is similar to yours, I'm running Kooha 2.2.4 installed via Flathub and on Debian 12 Wayland, and it fails to record in every mode.

**Comment by SeaDve** [comment] 2024-02-08 12:48
Closing as duplicate of https://github.com/SeaDve/Kooha/issues/129.

**Closed by SeaDve** 2024-02-08 12:48 UTC
