### ISSUE TITLE
Failed to start recording

### ISSUE THREAD

**Issue by scarf005** [SeaDve/Kooha#203] opened 2022-11-02 13:43 UTC
**System Info**
- io.github.seadve.Kooha 2.2.2
- Flatpak: true
- Experimental: false

- Distribution: GNOME 43 (Flatpak runtime)
- Desktop Session: plasma
- Display Server: x11

- GTK 4.8.2
- Libadwaita 1.2.0
- GStreamer 1.20.3
- Pipewire 0.3.57

**Describe the bug**
it fails to record.

**To Reproduce**
1. install kooha from flatpak
2. click 'record'

**Expected behavior**
it records.

**Screenshots**
![image](https://user-images.githubusercontent.com/54838975/199504439-079fa4d6-aba8-45ae-b3f2-c0a7fdb41c7a.png)

**Additional context**
```sh
RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=kooha io.github.seadve.Kooha
2022-11-02T13:39:23.111406Z  INFO kooha::application: Kooha (io.github.seadve.Kooha)
2022-11-02T13:39:23.111425Z  INFO kooha::application: Version: 2.2.2 ()
2022-11-02T13:39:23.111428Z  INFO kooha::application: Datadir: /app/share/kooha
2022-11-02T13:39:24.863699Z DEBUG kooha::screencast_session: Waiting request response for method `CreateSession`
2022-11-02T13:39:24.864404Z DEBUG kooha::screencast_session: Request response received for method `CreateSession`
2022-11-02T13:39:24.864590Z ERROR kooha::window: Failed to start recording

Caused by:
    0: Check out <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> for help.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Interaction was ended in some other way with response VariantDict({"session_handle": Variant { ptr: 0x55d362568a00, type: VariantTy { inner: "s" }, value: "'/org/freedesktop/portal/desktop/session/1_558/kooha_0'" }})
```

**Comment by LaurenceHo** [comment] 2023-05-22 02:17
Same here. And below is the information:
```
- io.github.seadve.Kooha 2.2.3
- Flatpak: true
- Experimental: false

- Distribution: GNOME 43 (Flatpak runtime)
- Desktop Session: ubuntu
- Display Server: x11

- GTK 4.8.3
- Libadwaita 1.2.4
- GStreamer 1.20.6
- Pipewire 0.3.69
```

**Comment by SeaDve** [comment] 2024-02-08 12:54
Closing as duplicate of https://github.com/SeaDve/Kooha/issues/202

**Closed by SeaDve** 2024-02-08 12:54 UTC
