### ISSUE TITLE
Failed to start recording on Linux Mint

### ISSUE THREAD

**Issue by BinaryShrub** [SeaDve/Kooha#266] opened 2023-12-03 22:47 UTC
Failed to start recording

Caused by:
    0: Check out <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> for help.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Failed to call `CreateSession` with parameters: Variant { ptr: 0x561b4f4e9990, type: VariantTy { inner: "(a{sv})" }, value: "({'handle_token': <'kooha_3'>, 'session_handle_token': <'kooha_2'>},)" }
    4: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

**Comment by SeaDve** [comment] 2024-02-08 12:48
Closing as duplicate of https://github.com/SeaDve/Kooha/issues/129.

**Closed by SeaDve** 2024-02-08 12:48 UTC
