### ISSUE TITLE
Mouse pointer is not visible in X11

### ISSUE THREAD

**Issue by prateekmedia** [SeaDve/Kooha#56] opened 2021-04-28 05:55 UTC
Video Recording:

https://user-images.githubusercontent.com/41370460/116356857-6f4e8e00-a819-11eb-8521-e0bfca433a78.mp4

Neofetch:
```css
          /:-------------:\          prateeksu@fedora 
       :-------------------::        ---------------- 
     :-----------/shhOHbmp---:\      OS: Fedora 34 (Workstation Edition) x86_64 
   /-----------omMMMNNNMMD  ---:     Kernel: 5.11.13-300.fc34.x86_64 
  :-----------sMMMMNMNMP.    ---:    Uptime: 1 hour, 2 mins 
 :-----------:MMMdP-------    ---\   Packages: 2444 (rpm), 14 (flatpak) 
,------------:MMMd--------    ---:   Shell: fish 3.2.1 
:------------:MMMd-------    .---:   Resolution: 1600x900 
:----    oNMMMMMMMMMNho     .----:   DE: GNOME 40.0 
:--     .+shhhMMMmhhy++   .------/   WM: Mutter 
:-    -------:MMMd--------------:    WM Theme: Adwaita 
:-   --------/MMMd-------------;     Theme: Adwaita-dark [GTK2/3] 
:-    ------/hMMMy------------:      Icons: Tela-dark [GTK2/3] 
:-- :dMNdhhdNMMNo------------;       Terminal: gnome-terminal 
:---:sdNMMMMNds:------------:        CPU: Intel Core 2 Quad Q9300 (4) @ 1.077GHz 
:------:://:-------------::          GPU: NVIDIA GeForce GT 1030 
:---------------------://            Memory: 3165MiB / 7950MiB 
```

with Xorg session

**Comment by SeaDve** [comment] 2021-04-28 11:30
Hmm, is it reproducible with wayland session?

**Comment by prateekmedia** [comment] 2021-04-28 12:47
> Hmm, is it reproducible with wayland session?

Actually Nvidia and Wayland doesn't pair up well but last month when I tried it on Wayland without Nvidia drivers then it worked AFAIK.

**Comment by SeaDve** [comment] 2021-04-28 12:50
Okay, thanks. It might be an xorg issue then. One more thing, if I may. Does it show the cursor when you press `ctrl+shift+alt+r` to record?

**Comment by prateekmedia** [comment] 2021-04-28 13:19
> Okay, thanks. It might be an xorg issue then. One more thing, if I may. Does it show the cursor when you press `ctrl+shift+alt+r` to record on xorg?

Yes.

**Comment by SeaDve** [comment] 2021-04-28 13:21
That's weird. I think it might be the app settings? Can you show ~/.var/app/io.github.seadve.Kooha/glib-2.0/keyfile ? It is where the configuration file is saved in flatpak. It includes there if it should actually include pointer.

**Comment by prateekmedia** [comment] 2021-04-29 08:08
Please wait will report it soon.

**Comment by prateekmedia** [comment] 2021-04-29 10:20
Ok here you go,
```css
[io/github/seadve/Kooha]
show-pointer=true
video-format='mkv'
```

**Comment by prateekmedia** [comment] 2021-04-29 15:31
Also note that it records cursor with simple screen recorder and default Ctrl+Alt+Shift+R keybindings.

But it doesn't work with kooha and also I tried with RecApp, it didn't recorded cursor.

**Comment by SeaDve** [comment] 2021-04-29 23:15
Thanks, i'll fix it

**Comment by charbelnicolas** [comment] 2021-05-06 14:24
I'm on X11, same issue, the pointer is not being recorded.

**Comment by SeaDve** [comment] 2021-05-06 21:46
> I tried with RecApp, it didn't recorded cursor.

RecApp uses different backend in X11. That's interesting

**Comment by SeaDve** [comment] 2021-06-02 13:56
Hi, i think this might be fixed on latest commits in portal branch

**Comment by prateekmedia** [comment] 2021-06-03 06:43
> Hi, i think this might be fixed on latest commits in portal branch
> 
> You can test it, if confirmed, I'll include this to 2.0.0 milestone, thanks

I cannot test it as I am in kde and v2 is also broke in kde.

**Comment by SeaDve** [comment] 2021-06-03 07:20
it should also work on kde, if they have interface for org.freedesktop.portal.Screencast

**Comment by SeaDve** [comment] 2021-06-09 03:48
Is it working?

**Comment by prateekmedia** [comment] 2021-06-09 04:04
> Is it working?

I cannot test it, no compile errors on kde but recording is not working.

I don't know the dependencies name for arch based distro.

**Comment by SeaDve** [comment] 2021-06-09 04:06
which kde distro?

**Comment by prateekmedia** [comment] 2021-06-09 04:07
J

> which kde distro? I think it doesn't work with distros based on Ubuntu 20.04 and below, such as Neon

Manjaro kde

**Comment by SeaDve** [comment] 2021-06-09 04:08
I'll try to test it on my device, I'll install kde

**Comment by SeaDve** [comment] 2021-06-18 04:12
I am able to reproduce it in both 1.2.1 and main branch. The cursor is not really hidden, it is stuck on the top left most corner. I'm not sure what is causing it.

**Comment by SeaDve** [comment] 2021-06-18 04:28
I don't think the submitted issue could get that much attention from portal developers since one of portal main purpose is to improve wayland support with stuffs like recording, and not X11

**Comment by prateekmedia** [comment] 2021-06-18 05:24
Ok if not kooha then

**Comment by SeaDve** [comment] 2021-06-18 05:26
It would be better to keep it open, to keep tract of it

**Comment by working-name** [comment] 2021-07-15 13:01
> > Okay, thanks. It might be an xorg issue then. One more thing, if I may. Does it show the cursor when you press `ctrl+shift+alt+r` to record on xorg?
> 
> Yes.

On my system the cursor is stuck at the top left with Xorg's own recorder as well. Kooha's settings didn't have cursor enabled although UI showed it, but toggling that button rewrote the config. Issue still remains.

So this is an Xorg issue altogether, am I right?

**Comment by SeaDve** [comment] 2021-07-15 13:11
> So this is an Xorg issue altogether, am I right?

correct, as far as i know

using ffmpeg is not a good idea, as it will need total rewrite of backend

**Comment by working-name** [comment] 2021-07-15 13:20
> using ffmpeg is not a good idea, as it will need total rewrite of backend

Sorry, it was this specific workaround:

```
A temporary workaround, until fixed gnome-shell is released, 
is to go to Gnome Settings -> Universal Access -> Zoom -> Magnifier 
and enable it with magnification 1.00. 

You'll get much worse cursor performance (and higher CPU utilization) though.
```

**Comment by SeaDve** [comment] 2021-07-15 13:42
I see, thanks! It may be helpful for others

**Closed** 2024-02-08 12:24 UTC
Labels: bug, upstream bug
