### ISSUE TITLE
Can not initialize x264 encoder

### ISSUE THREAD

**Issue by gui-milky** [SeaDve/Kooha#139] opened 2021-11-11 11:13 UTC
**System Info**
- Kooha version 2.0.1
- Fedora 35 Workstation
- GNOME 41
- Wayland
- Flatpak

**Describe the bug**
Recording Error cannot initialize x264 encoder

**To Reproduce**
1. Go to 'Save as MP4'
2. Click on 'Record'
3. Recording Error cannot initialize x264 encoder

**Expected behavior**
Starting Recording

**Screenshots**
![image](https://user-images.githubusercontent.com/22163948/141288244-381c11e7-1abe-4dae-90b6-0b4f8b1a6b18.png)

Notes
-I've installed Multimedia codecs from Rpmfusion

**Comment by SeaDve** [comment] 2021-12-16 01:12
could you run kooha with the following command: `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 flatpak run io.github.seadve.Kooha`

**Comment by gui-milky** [comment] 2021-12-17 15:02
https://pastebin.com/qgm5rHj9

**Comment by SeaDve** [comment] 2022-08-06 03:12
This is apparently caused by odd (not even) resolution. This should be fixed on the next release.

**Closed** 2022-08-06 03:15 UTC

**Comment by vogonwann** [comment] 2025-02-01 17:01
Hi. I'm facing the same issue on postmarketOS (gnome-mobile). It was working until yesterday. Here's log: http://0x0.st/88Fe.log
