### ISSUE TITLE
kooha CLI

### ISSUE THREAD

**Issue by majesticio** [SeaDve/Kooha#321] opened 2024-10-16 03:52 UTC
**Feature summary**

Use kooha from the command line

**How would you like it to work**

Perhaps something like `kooha -t 10 -a pipewire` which would record the screen for 10 seconds with audio.
Even basic functionality from the command line would be really handy.

**Comment by SeaDve** [comment] 2024-10-16 08:04
Thanks for reporting! This seems a duplicate of https://github.com/SeaDve/Kooha/issues/315

**Closed by SeaDve** 2024-10-16 08:04 UTC
