### ISSUE TITLE
Unexpectedly fails when clicking stop on share indicator in GNOME

### ISSUE THREAD

**Issue by darkblaze69** [SeaDve/Kooha#318] opened 2024-10-02 09:09 UTC
**Affected version**
* kooha 2.3.0
* GNOME 47.0
* Arch Linux

**Bug summary**

Unexpectedly fails when clicking stop on share indicator in GNOME

**Steps to reproduce**

1. Start recording
2. Click on stop in share indicators in GNOME
3. See error

**Expected behavior**
Correctly stops recording

**Relevant logs, screenshots, screencasts, etc.**

![Screenshot From 2024-10-02 14-07-30](https://github.com/user-attachments/assets/6eb4a6e0-26fa-46ef-871b-698b06c5bf44)

![image](https://github.com/user-attachments/assets/4bc0f054-aec3-4062-b7a8-397ad04d2715)

```
An error occurred while recording

Caused by:
    0: ../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasesrc.c(3177): gst_base_src_loop (): /GstPipeline:pipeline4/GstBin:kooha-pipewiresrc-bin/GstPipeWireSrc:pipewiresrc4:
       streaming stopped, reason not-negotiated (-4)
    1: Internal data stream error.
```

**Comment by SeaDve** [comment] 2024-10-11 01:18
Thanks for reporting! This seems a duplicate of https://github.com/SeaDve/Kooha/issues/287, so I'll refer with the other one.

**Closed by SeaDve** 2024-10-11 01:18 UTC
