### ISSUE TITLE
Mouse pointer not recorded in Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by digeomel** [SeaDve/Kooha#223] opened 2023-02-02 18:59 UTC
**System Info**
- io.github.seadve.Kooha 2.2.3
- Flatpak: true
- Experimental: false

- Distribution: GNOME 43 (Flatpak runtime)
- Desktop Session: ubuntu
- Display Server: x11

- GTK 4.8.3
- Libadwaita 1.2.1
- GStreamer 1.20.5
- Pipewire 0.3.59

**Describe the bug**
The mouse pointer is not recorded, although the option is set in the main menu:

![image](https://user-images.githubusercontent.com/3295889/216422303-c9afc0f0-0d75-4f1b-98d3-e25916e556ef.png)

**To Reproduce**
Just try to record a screen area with the mouse pointer option on. Format is MP4, frame-rate is 30. It makes no difference if it is on the main or secondary monitor.

**Expected behavior**
I expect the mouse pointer to appear on the video.

**Comment by mohsenjavidpanah** [comment] 2023-11-21 21:17
I have same problem on the Archlinux and Gnome desktop

**Comment by SeaDve** [comment] 2024-02-08 04:09
Closing as duplicate of https://github.com/SeaDve/Kooha/issues/56

**Closed by SeaDve** 2024-02-08 04:09 UTC
