### ISSUE TITLE
Unable to capture my screen on ubuntu 22.04

### ISSUE THREAD

**Issue by OmidEsmailbeig** [SeaDve/Kooha#245] opened 2023-06-13 16:10 UTC
**System Info**
- io.github.seadve.Kooha 2.2.3
- Flatpak: true
- Experimental: false

- Distribution: GNOME 43 (Flatpak runtime)
- Desktop Session: ubuntu
- Display Server: x11

- GTK 4.8.3
- Libadwaita 1.2.4
- GStreamer 1.20.6
- Pipewire 0.3.69

**Describe the bug**
I cannot record my screen, the detailed log is pasted in application context section.

**To Reproduce**
1. Open Kooha
2. Click on Record
3. See error

**Additional context**
Failed to start recording

Caused by:
    0: Check out <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> for help.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Failed to call `CreateSession` with parameters: Variant { ptr: 0x55f5a5c96f80, type: VariantTy { inner: "(a{sv})" }, value: "({'handle_token': <'kooha_3'>, 'session_handle_token': <'kooha_2'>},)" }
    4: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

**Comment by Raxelgrande** [comment] 2023-06-14 04:41
Unfortunately, this was done quietly without asking for maintainers. But Kooha's main developer is giving Kooha minimal maintenance, mainly to focus on his other app, Mousai. 
This is why you see multiple bug reports on all sorts of distros with mayor errors. 

Until you get help, my advice is that you use OBS for Wayland recording or use one of the X11 screen recorders (simplescreenrecorder and kazam are the best). 
If OBS doesn't work, it's likely your Ubuntu has some trouble related to "xdg-desktop-portal" because that's the error Kooha gives, I'm not a developer, so it's just a guess.

**Comment by SeaDve** [comment] 2024-02-08 12:49
Closing as duplicate of https://github.com/SeaDve/Kooha/issues/129.

**Closed by SeaDve** 2024-02-08 12:49 UTC
