### ISSUE TITLE
Starting fails with "cannot open display"

### ISSUE THREAD

**Issue by nethad** [SeaDve/Kooha#32] opened 2021-03-19 08:06 UTC
I tried running Kooha and got the following error:

```
$ flatpak run io.github.seadve.Kooha

(io.github.seadve.Kooha:2): Gtk-WARNING **: 09:00:40.407: cannot open display: 
```

I tried this after just opening it the normal way and not seeing a window. I'm running Fedora 33 (with all the latest packages) and Wayland. I tried starting an X11 session and get the same error, so I assume it's not a Wayland issue.

```
$ flatpak list | grep Kooha
Kooha	io.github.seadve.Kooha	1.0.3	stable	flathub	system
```

Any idea how I can solve this issue?

**Comment by SeaDve** [comment] 2021-03-19 08:15
Does other flatpak apps have the same behavior?

**Comment by nethad** [comment] 2021-03-19 08:19
@SeaDve  No, I started a few other apps also with `flatpak run` and they do work. Let me know if you need any more information :+1:

**Comment by SeaDve** [comment] 2021-03-19 08:42
Does it never launch?

**Comment by SeaDve** [comment] 2021-03-19 08:51
I just updated my machine to the latest Fedora release and reinstalled the app, I wasn't able to replicate it.
Try clearing the cache of the app in /home/.var/app/io.github.seadve.Kooha, deleting it would be fine.

**Comment by SeaDve** [comment] 2021-03-19 08:56
Normally, from the gnome-software, installed in the system.

**Comment by SeaDve** [comment] 2021-03-19 08:59
Would you like to try building it from source? If it might be a flatpak issue. Sorry, if I got too many questions, it's a pretty new issue to me.

**Comment by nethad** [comment] 2021-03-19 09:03
@SeaDve  Hmm, this is pretty weird, when I install via Gnome Software, it works! Sorry about that, but I copied the command from flathub.org:

```
flatpak install flathub io.github.seadve.Kooha
```

I've done this with other flatpaks as well and it worked in the past. Do you have an idea why this could happen? Should I report this to Fedora or Flatpak?

Either way, thanks for your help so far!

**Comment by SeaDve** [comment] 2021-03-19 09:06
That is really, really, really weird. I have no idea either, currently researching about it, and I'm still not enlightened. You're welcome, you may close the issue. Although, I'll try to find the root cause

**Closed** 2021-03-19 09:07 UTC
