### ISSUE TITLE
Add support with other desktop environments

### ISSUE THREAD

**Issue by telmobss1** [SeaDve/Kooha#10] opened 2021-03-14 11:59 UTC
My request was to adapt the application to record videos on lxqt, kde xfce, cinamon mate budgie making the application make independent of gnome

I would also like an application in qt, but in this case it would be a superficial thing and therefore would be careful from those who develop

**Comment by SeaDve** [comment] 2021-03-14 12:02
Support with other desktop environments is part of roadmap to v2.0

**Comment by TheOPtimal** [comment] 2021-03-17 08:09
> My request was to adapt the application to record videos on lxqt, kde xfce, cinamon mate budgie making the application make independent of gnome
> 
> I would also like an application in qt, but in this case it would be a superficial thing and therefore would be careful from those who develop

**Comment by TheOPtimal** [comment] 2021-03-17 08:09
> My request was to adapt the application to record videos on lxqt, kde xfce, cinamon mate budgie making the application make independent of gnome
> 
> I would also like an application in qt, but in this case it would be a superficial thing and therefore would be careful from those who develop

I think it's best for this application to stay on GNOME, there are other great screen recorders for other DEs.

**Comment by SeaDve** [comment] 2021-05-26 12:00
#65 working on it

**Comment by SeaDve** [comment] 2021-06-17 03:42
Hi, would like to confirm if kooha now works on certain 
your desktop environment. it would be great to build main branch or this already 
built package https://github.com/SeaDve/Kooha/suites/3015646991/artifacts/68284776
If there are problems, ill do my best to fix it and support KDE, elementary etc.

**Comment by Ygor-Elinaldo** [comment] 2023-02-03 13:00
I reiceved this when trying to record on my elementaryOS 7: 

Falha ao iniciar gravação
Caused by:
    0: Verifique <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> para receber ajuda.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Failed to call `CreateSession` with parameters: Variant { ptr: 0x5644c696adc0, type: VariantTy { inner: "(a{sv})" }, value: "({'session_handle_token': <'kooha_2'>, 'handle_token': <'kooha_3'>},)" }
    4: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Nenhuma interface “org.freedesktop.portal.ScreenCast” no objeto no caminho /org/freedesktop/portal/desktop

**Comment by SeaDve** [comment] 2024-02-08 12:16
Closing as completed. As long as your DE has `ScreenCast` portal, it should work, otherwise, please report it here. Thanks!

**Closed by SeaDve** 2024-02-08 12:16 UTC
Labels: enhancement
