### ISSUE TITLE
Recording Error message + no saved video.

### ISSUE THREAD

**Issue by mprater** [SeaDve/Kooha#163] opened 2022-04-08 00:24 UTC
**System Info**
Kooha 2.0.1
Red Hat 8
Gnome
xorg x11
I used the gnome software tool to find/install Kooha.

**Describe the bug**
After selecting which window to record and then clicking the Kooha Record button; I then fiddle around with the window's content; then I click the Kooha Record button again. Neither the first or second clicking of the Record button provides any feedback. A few seconds after clicking the Record button for the second time (I assume to stop recording), the error dialog pops up saying "stream error: wrong resource type/version. In the saving location there will be a new file such as Kooha-04-07-2022-16-52-53.mp4, but the file is 0 length. I've tried all video formats but get the same result.

**To Reproduce**
See above.

**Expected behavior**
Expect to find a file that contains the recorded video and audio.

**Screenshots**

**Additional context**puter:~:{05:22:49}`RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 flatpak run io.github.seadve.Kooha`
 INFO  kooha::application > Kooha (io.github.seadve.Kooha)
 INFO  kooha::application > Version: 2.0.1 ()
 INFO  kooha::application > Datadir: /app/share/kooha
 DEBUG kooha::backend::recorder > is_show_pointer: true
 DEBUG kooha::backend::recorder > is_selection_mode: false
 INFO  kooha::backend::screencast_portal > ScreenCastProxy created
 DEBUG kooha::backend::screencast_portal > available_cursor_modes: BitFlags<CursorMode>(0b111, Hidden | Embedded | Metadata)
 DEBUG kooha::backend::screencast_portal > available_source_types: BitFlags<SourceType>(0b11, Monitor | Window)
 INFO  kooha::backend::screencast_portal > Session created
 INFO  kooha::backend::screencast_portal > Select sources window showed
 INFO  kooha::backend::screencast_portal > Screencast session started
 INFO  kooha::backend::screencast_portal > Ready for pipewire stream
 DEBUG kooha::backend::recorder          > pulse_server_version: pulseaudio version 14.0-rebootstrapped
 DEBUG kooha::backend::recorder          > PipelineBuilder { is_record_speaker: true, is_record_mic: true, framerate: 30, file_path: "/home/mprater/Videos/Kooha-04-07-2022-17-23-18.mkv", fd: 31, streams: [Stream { pipewire_node_id: 92, position: None, size: Some((2560, 1600)) }], speaker_source: Some("alsa_output.pci-0000_00_1f.3.analog-stereo.monitor"), mic_source: Some("alsa_input.usb-046d_HD_Webcam_C615_60E042F0-00.mono-fallback"), coordinates: None, actual_screen: None }
 DEBUG kooha::backend::pipeline_builder  > is_use_vaapi: false
 DEBUG kooha::backend::pipeline_builder  > pipeline_string: queue name=queue0 ! videorate ! video/x-raw, framerate=30/1 ! videoconvert chroma-mode=GST_VIDEO_CHROMA_MODE_NONE dither=GST_VIDEO_DITHER_NONE matrix-mode=GST_VIDEO_MATRIX_MODE_OUTPUT_ONLY n-threads=52 ! queue ! vp8enc max_quantizer=17 cpu-used=16 cq_level=13 deadline=1 static-threshold=100 keyframe-mode=disabled buffer-size=20000 threads=52 ! queue ! matroskamux name=mux ! filesink name=filesink location="/home/mprater/Videos/Kooha-04-07-2022-17-23-18.mkv" pipewiresrc fd=31 path=92 do-timestamp=true keepalive-time=1000 resend-last=true ! video/x-raw, max-framerate=30/1 ! queue0. pulsesrc device="alsa_output.pci-0000_00_1f.3.analog-stereo.monitor" ! queue ! audiomixer name=mix ! opusenc ! queue ! mux. pulsesrc device="alsa_input.usb-046d_HD_Webcam_C615_60E042F0-00.mono-fallback" ! queue ! mix.
[I][29373.080648][      pipewire.c:  571 pw_init()] version 0.3.35
[I][29373.085190][          conf.c:  326 conf_load()] config 0x55f7132b7490: loading config '/usr/share/pipewire/client.conf'
[I][29373.085236][       context.c:  384 pw_context_new()] context 0x55f713495740: parsed context.properties section
[I][29373.085614][       context.c:  478 pw_context_new()] context 0x55f713495740: parsed 2 context.spa-libs items
[I][29373.085835][          conf.c:  419 load_module()] config 0x55f713495740: loaded module libpipewire-module-protocol-native
[I][29373.086098][          conf.c:  419 load_module()] config 0x55f713495740: loaded module libpipewire-module-client-node
[I][29373.086240][          conf.c:  419 load_module()] config 0x55f713495740: loaded module libpipewire-module-client-device
[I][29373.086382][          conf.c:  419 load_module()] config 0x55f713495740: loaded module libpipewire-module-adapter
[I][29373.086512][          conf.c:  419 load_module()] config 0x55f713495740: loaded module libpipewire-module-metadata
[I][29373.086669][          conf.c:  419 load_module()] config 0x55f713495740: loaded module libpipewire-module-session-manager
[I][29373.086680][       context.c:  482 pw_context_new()] context 0x55f713495740: parsed 6 context.modules items
[I][29373.086689][       context.c:  487 pw_context_new()] context 0x55f713495740: parsed 0 context.objects items
[I][29373.086697][       context.c:  490 pw_context_new()] context 0x55f713495740: parsed 0 context.exec items
[I][29373.086728][       context.c:  244 context_set_freewheel()] context 0x55f713495740: exit freewheel
[I][29373.086740][       context.c:  248 context_set_freewheel()] context 0x55f713495740: freewheel error:Operation not supported
[I][29373.086752][ impl-metadata.c:  196 impl_set_property()] metadata 0x55f713507e00: add id:0 key:log.level type: value:0
[I][29373.086761][ impl-metadata.c:  196 impl_set_property()] metadata 0x55f713507e00: add id:0 key:clock.min-quantum type: value:32
[I][29373.086770][ impl-metadata.c:  196 impl_set_property()] metadata 0x55f713507e00: add id:0 key:clock.max-quantum type: value:8192
[I][29373.086778][ impl-metadata.c:  196 impl_set_property()] metadata 0x55f713507e00: add id:0 key:clock.force-quantum type: value:0
[I][29373.086785][ impl-metadata.c:  196 impl_set_property()] metadata 0x55f713507e00: add id:0 key:clock.force-rate type: value:0
0:00:27.088098631     2 0x55f712d9c0c0 WARN              aggregator gstaggregator.c:2050:gst_aggregator_query_latency_unlocked:<mix> Latency query failed
0:00:27.088137135     2 0x7f1878159b00 FIXME                default gstutils.c:4025:gst_pad_create_stream_id_internal:<pulsesrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:27.088141027     2 0x7f1878159b60 FIXME                default gstutils.c:4025:gst_pad_create_stream_id_internal:<pulsesrc1:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:27.088195256     2 0x55f712d9c0c0 WARN              aggregator gstaggregator.c:2050:gst_aggregator_query_latency_unlocked:<mix> Latency query failed
0:00:27.088379692     2 0x7f1878128e40 FIXME                default gstutils.c:4025:gst_pad_create_stream_id_internal:<pipewiresrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
[E][29373.088584][        stream.c:  365 stream_set_state()] stream 0x55f71350c360: error wrong resource type/version
0:00:27.089254101     2 0x55f7132bca00 WARN             pipewiresrc gstpipewiresrc.c:529:on_state_changed:<pipewiresrc0> error: stream error: wrong resource type/version
[W][29373.088838][gstpipewirecore.:   42 on_core_error()] error id:2 seq:2 res:-71 (Protocol error): wrong resource type/version
[W][29373.088858][     impl-node.c:  388 suspend_node()] node 0x7f182000c6c0: error unset format input: Input/output error
[I][29373.088868][     impl-node.c:  358 node_update_state()] (kooha-0) creating -> suspended
[W][29373.088881][gstpipewirecore.:   42 on_core_error()] error id:0 seq:3 res:-22 (Invalid argument): unknown resource 2 op:2
[W][29373.088890][gstpipewirecore.:   42 on_core_error()] error id:0 seq:4 res:-22 (Invalid argument): unknown resource 2 op:3

^C

**Comment by mprater** [comment] 2022-04-08 23:07
I tried building locally using these instructions: https://github.com/SeaDve/Kooha#%EF%B8%8F-building-from-source

Build succeeded, but produced similar runtime errors when launched from Gnome Builder:

Application started at 04:01:51 PM
0:00:00.006030899     3 0x564400dcad90 WARN                   vaapi gstvaapiutils.c:78:gst_vaapi_warning: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
0:00:00.006207826     3 0x564400dcad90 WARN                   vaapi gstvaapiutils.c:78:gst_vaapi_warning: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
0:00:00.007678897     3 0x564400dcad90 WARN                 default gstvaapi.c:231:plugin_init: Cannot create a VA display
[I][28910.264196][      pipewire.c:  571 pw_init()] version 0.3.35
0:00:00.388135393     3 0x564400dcad90 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0x120000: 'AVR (Audio Visual Research)' is not mapped
0:00:00.388167357     3 0x564400dcad90 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0x180000: 'CAF (Apple Core Audio File)' is not mapped
0:00:00.388192942     3 0x564400dcad90 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0x100000: 'HTK (HMM Tool Kit)' is not mapped
0:00:00.388230109     3 0x564400dcad90 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0xc0000: 'MAT4 (GNU Octave 2.0 / Matlab 4.2)' is not mapped
0:00:00.388277664     3 0x564400dcad90 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0xd0000: 'MAT5 (GNU Octave 2.1 / Matlab 5.0)' is not mapped
0:00:00.388325902     3 0x564400dcad90 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0x210000: 'MPC (Akai MPC 2k)' is not mapped
0:00:00.388388043     3 0x564400dcad90 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0xe0000: 'PVF (Portable Voice Format)' is not mapped
0:00:00.388440395     3 0x564400dcad90 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0x160000: 'SD2 (Sound Designer II)' is not mapped
0:00:00.388495845     3 0x564400dcad90 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0x190000: 'WVE (Psion Series 3)' is not mapped
 INFO  kooha::application > Kooha (io.github.seadve.Kooha.Devel)
 INFO  kooha::application > Version: 2.0.1-63ecf4c (Devel)
 INFO  kooha::application > Datadir: /app/share/kooha

(kooha:2): Gtk-CRITICAL **: 16:01:51.684: Unable to connect to the accessibility bus at 'unix:abstract=/tmp/dbus-J3sUT8gOFS,guid=ac1909d539efd047373dce2162504e28': Could not connect: Connection refused
 DEBUG kooha::backend::recorder > is_show_pointer: true
 DEBUG kooha::backend::recorder > is_selection_mode: false
 INFO  kooha::backend::screencast_portal > ScreenCastProxy created
 DEBUG kooha::backend::screencast_portal > available_cursor_modes: BitFlags<CursorMode>(0b111, Hidden | Embedded | Metadata)
 DEBUG kooha::backend::screencast_portal > available_source_types: BitFlags<SourceType>(0b11, Monitor | Window)
 INFO  kooha::backend::screencast_portal > Session created
 INFO  kooha::backend::screencast_portal > Select sources window showed
 INFO  kooha::backend::screencast_portal > Screencast session started
 INFO  kooha::backend::screencast_portal > Ready for pipewire stream
 DEBUG kooha::backend::recorder          > pulse_server_version: pulseaudio version 14.0-rebootstrapped
 DEBUG kooha::backend::recorder          > PipelineBuilder { is_record_speaker: false, is_record_mic: false, framerate: 30, file_path: "/home/mprater/Videos/Kooha-2022-04-08-16-03-17.webm", fd: 30, streams: [Stream { pipewire_node_id: 86, position: None, size: Some((2560, 1600)) }], speaker_source: Some("alsa_output.pci-0000_00_1f.3.analog-stereo.monitor"), mic_source: Some("alsa_input.usb-046d_HD_Webcam_C615_60E042F0-00.mono-fallback"), coordinates: None, actual_screen: None }
 DEBUG kooha::backend::pipeline_builder  > is_use_vaapi: false
 DEBUG kooha::backend::pipeline_builder  > pipeline_string: queue name=queue0 ! videorate ! video/x-raw, framerate=30/1 ! videoconvert chroma-mode=GST_VIDEO_CHROMA_MODE_NONE dither=GST_VIDEO_DITHER_NONE matrix-mode=GST_VIDEO_MATRIX_MODE_OUTPUT_ONLY n-threads=52 ! queue ! vp8enc max_quantizer=17 cpu-used=16 cq_level=13 deadline=1 static-threshold=100 keyframe-mode=disabled buffer-size=20000 threads=52 ! queue ! webmmux name=mux ! filesink name=filesink location="/home/mprater/Videos/Kooha-2022-04-08-16-03-17.webm" pipewiresrc fd=30 path=86 do-timestamp=true keepalive-time=1000 resend-last=true ! video/x-raw, max-framerate=30/1 ! queue0. 
[I][28996.196437][      pipewire.c:  571 pw_init()] version 0.3.35
[I][28996.198348][          conf.c:  326 conf_load()] config 0x55804381dbd0: loading config '/usr/share/pipewire/client.conf'
[I][28996.198385][       context.c:  384 pw_context_new()] context 0x5580437c9410: parsed context.properties section
[I][28996.198872][       context.c:  478 pw_context_new()] context 0x5580437c9410: parsed 2 context.spa-libs items
[I][28996.199163][          conf.c:  419 load_module()] config 0x5580437c9410: loaded module libpipewire-module-protocol-native
[I][28996.199405][          conf.c:  419 load_module()] config 0x5580437c9410: loaded module libpipewire-module-client-node
[I][28996.199518][          conf.c:  419 load_module()] config 0x5580437c9410: loaded module libpipewire-module-client-device
[I][28996.199636][          conf.c:  419 load_module()] config 0x5580437c9410: loaded module libpipewire-module-adapter
[I][28996.199741][          conf.c:  419 load_module()] config 0x5580437c9410: loaded module libpipewire-module-metadata
[I][28996.199874][          conf.c:  419 load_module()] config 0x5580437c9410: loaded module libpipewire-module-session-manager
[I][28996.199879][       context.c:  482 pw_context_new()] context 0x5580437c9410: parsed 6 context.modules items
[I][28996.199883][       context.c:  487 pw_context_new()] context 0x5580437c9410: parsed 0 context.objects items
[I][28996.199887][       context.c:  490 pw_context_new()] context 0x5580437c9410: parsed 0 context.exec items
[I][28996.199923][       context.c:  244 context_set_freewheel()] context 0x5580437c9410: exit freewheel
[I][28996.199929][       context.c:  248 context_set_freewheel()] context 0x5580437c9410: freewheel error:Operation not supported
[I][28996.199935][ impl-metadata.c:  196 impl_set_property()] metadata 0x558043820290: add id:0 key:log.level type: value:0
[I][28996.199940][ impl-metadata.c:  196 impl_set_property()] metadata 0x558043820290: add id:0 key:clock.min-quantum type: value:32
[I][28996.199946][ impl-metadata.c:  196 impl_set_property()] metadata 0x558043820290: add id:0 key:clock.max-quantum type: value:8192
[I][28996.199951][ impl-metadata.c:  196 impl_set_property()] metadata 0x558043820290: add id:0 key:clock.force-quantum type: value:0
[I][28996.199954][ impl-metadata.c:  196 impl_set_property()] metadata 0x558043820290: add id:0 key:clock.force-rate type: value:0
0:01:26.314905602     2 0x558040cbbea0 FIXME                default gstutils.c:4025:gst_pad_create_stream_id_internal:<pipewiresrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
[E][28996.201794][        stream.c:  365 stream_set_state()] stream 0x5580437e35e0: error wrong resource type/version
0:01:26.315821786     2 0x7f29d80058f0 WARN             pipewiresrc gstpipewiresrc.c:529:on_state_changed:<pipewiresrc0> error: stream error: wrong resource type/version
[W][28996.201899][gstpipewirecore.:   42 on_core_error()] error id:2 seq:2 res:-71 (Protocol error): wrong resource type/version
[W][28996.201910][     impl-node.c:  388 suspend_node()] node 0x7f29d800c9b0: error unset format input: Input/output error
[I][28996.201918][     impl-node.c:  358 node_update_state()] (kooha-0) creating -> suspended
[W][28996.201926][gstpipewirecore.:   42 on_core_error()] error id:0 seq:3 res:-22 (Invalid argument): unknown resource 2 op:2
[W][28996.201932][gstpipewirecore.:   42 on_core_error()] error id:0 seq:4 res:-22 (Invalid argument): unknown resource 2 op:3
 ERROR kooha::backend::recorder::imp     > Failed to set pipeline state to Playing: StateChangeError
0:01:56.315828709     2 0x558040cbbea0 WARN                 basesrc gstbasesrc.c:3127:gst_base_src_loop:<pipewiresrc0> error: Internal data stream error.
0:01:56.315862427     2 0x558040cbbea0 WARN                 basesrc gstbasesrc.c:3127:gst_base_src_loop:<pipewiresrc0> error: streaming stopped, reason not-negotiated (-4)
 INFO  kooha::backend::recorder          > Pipeline state set from Null -> Ready
0:01:56.316959077     2 0x558040c1e600 WARN               structure gststructure.c:2069:priv_gst_structure_append_to_gstring: No value transform to serialize field 'gerror' of type 'GError'
 ERROR kooha::backend::recorder          > Error from record bus: Error { domain: gst-resource-error-quark, code: 1, message: "stream error: wrong resource type/version" } (debug Error(Message { ptr: 0x7f29d8001b90, type: "error", seqnum: 67, src: Some("pipewiresrc0"), structure: Some(GstMessageError, gerror=(GError)NULL, debug=(string)"../src/gst/gstpipewiresrc.c\(529\):\ on_state_changed\ \(\):\ /GstPipeline:pipeline0/GstPipeWireSrc:pipewiresrc0";) }))
[I][29026.202981][     impl-node.c: 1736 pw_impl_node_destroy()] (kooha-0) destroy
 INFO  kooha::backend::screencast_portal > Session closed

**Comment by wolfred24** [comment] 2022-04-18 17:52
Same issue here

**Comment by stpnwf** [comment] 2022-05-03 17:03
Same issue on Zorin OS 16

**Comment by sysfu** [comment] 2022-06-10 20:16
also experiencing this on PureOS Byzantium with Kooha 2.0.1 from flathub

**Comment by SeaDve** [comment] 2022-08-16 11:36
Thanks for reporting! I'll be closing this though as a duplicate of #129. Also, this [comment](https://github.com/SeaDve/Kooha/issues/129#issuecomment-1060293459) might be helpful, and probably document it in the application in the future.

**Closed by SeaDve** 2022-08-16 11:36 UTC

**Comment by sysfu** [comment] 2022-08-16 14:59
> Thanks for reporting! I'll be closing this though as a duplicate of #129. Also, this [comment](https://github.com/SeaDve/Kooha/issues/129#issuecomment-1060293459) might be helpful, and probably document it in the application in the future.

Thanks for the link to the comment with the workaround. Unfortunately the given package names don't match up for PureOS systems.
