### ISSUE TITLE
Selection region is off on integer scaling

### ISSUE THREAD

**Issue by dmoebius** [SeaDve/Kooha#18] opened 2021-03-16 14:10 UTC
Arch Linux, using Kooha 1.0.2, installed from AUR https://aur.archlinux.org/packages/kooha

I have a Hi-DPI screen with 3840x2160 pixels, 290 dpi. GNOME display scaled to 200%.

When I record a screen region, it seems that the real coordinates of the rectangle that defines the region are off by one half. Ie. when I define to record the region from (200,200) to (500,500), Kooha really records the region from (100,100) to (250,250).

**Comment by SeaDve** [comment] 2021-03-16 14:13
Thanks for submitting the issue! It uses a method of the dbus interface in the gnome shell. Try using built-in screenshot tool (GNOME screenshot) if you can replicate the bug.

**Comment by dmoebius** [comment] 2021-03-16 14:29
GNOME screenshot works fine; it records exactly the region I selected.

**Comment by SeaDve** [comment] 2021-03-16 14:34
I'll investigate on it.

**Comment by dmoebius** [comment] 2021-03-16 14:35
Just FYI, when I set GNOME's screen scale to 100% it records the correct region.

**Comment by SeaDve** [comment] 2021-03-17 01:16
Not replicable on my end. I set up my display to be 175%, and it still records the correct area. It might be that you set it to 200%? I can't seem to find that option.

**Comment by HaasJona** [comment] 2021-03-18 11:19
GNOME by default only allows scaling to integers, eg 100%, 200%, 300%, you might have experimental fractional scaling enabled or an experimental/hacked version installed.

**Comment by SeaDve** [comment] 2021-03-18 11:26
I cannot find the options for integer scaling, maybe only available from hidpi's?

**Comment by HaasJona** [comment] 2021-03-19 15:20
I can confirm this issue. I use 200% scaling and the recorded coordinates are all 200% too small.

https://user-images.githubusercontent.com/4310707/111803001-eb76bd00-88ce-11eb-8e65-0fafae18bdc8.mp4

https://user-images.githubusercontent.com/4310707/111803025-ef0a4400-88ce-11eb-831d-c469a3835b17.mp4

![Bildschirmfoto von 2021-03-19 16-20-05](https://user-images.githubusercontent.com/4310707/111803067-fa5d6f80-88ce-11eb-87a4-a72684d94675.png)

**Comment by SeaDve** [comment] 2021-06-04 00:53
Hi, I'm thinking of removing selection support, so I would like to know your opinions whether its the right choice. The reason is that it will be useless, since it would be possible now to select a specific monitor, or window to record.

**Comment by dodalovic** [comment] 2021-06-04 05:05
For me, personally, it's an essential feature. This would force me to find another tool.

**Comment by dmoebius** [comment] 2021-06-04 09:59
For me, it's an essential feature, too. I use this feature to crop off sensitive sections of my screen that I don't want to share in the recorded video.
I don't understand why you would remove such a useful feature. Besides the scaling issue it works very well.

**Comment by SeaDve** [comment] 2021-06-11 01:28
I'm working on it, besides maintaining the feature, I'll support other desktop environments and fix this scaling issue. Check #73

**Comment by SeaDve** [comment] 2021-06-11 04:20
I found the issue, it was that the original resolution should be divided by the actual resolutions of your screen then multiply back to x, y width and height

**Comment by SeaDve** [comment] 2021-06-13 01:09
pushed the fix in development branch :D

**Comment by SeaDve** [comment] 2021-06-17 03:39
fix merged to main branch

**Closed by SeaDve** 2021-06-17 03:39 UTC
Labels: bug

**Comment by dodalovic** [comment] 2021-06-17 08:35
@SeaDve Is there any rough estimate of when the new release will be available? Thanks for the fix!!!!

**Comment by SeaDve** [comment] 2021-06-17 08:36
Possibly after the release of GTK 4.3.3

**Comment by dmoebius** [comment] 2021-08-24 11:51
Sorry for the late response (have been very busy). I verified that the fix works. Many thanks!! :smiley: :+1:
